#ifndef GUARD_CONSTANTS_FIELD_MUGSHOTS_H
#define GUARD_CONSTANTS_FIELD_MUGSHOTS_H

enum Mugshots {
    MUGSHOT_NONE = 0,
    MUGSHOT_YOUNGSTER,
    MUGSHOT_FALKNER,
    MUGSHOT_BUG_CATCHER,
    MUGSHOT_ELM,
    MUGSHOT_SILVER,
    MUGSHOT_LASS,
    MUGSHOT_PICNICKER,
    MUGSHOT_CAMPER,
    MUGSHOT_FISHERMAN,
    MUGSHOT_HIKER,
    MUGSHOT_BLACK_BELT,
    MUGSHOT_ROCKET_GRUNT_M,
    MUGSHOT_ROCKET_GRUNT_F,
    MUGSHOT_WILL,
    MUGSHOT_KOGA,
    MUGSHOT_BRUNO,
    MUGSHOT_KAREN,
    MUGSHOT_BUGSY,
    MUGSHOT_WHITNEY,
    MUGSHOT_MORTY,
    MUGSHOT_JASMINE,
    MUGSHOT_CHUCK,
    MUGSHOT_PRYCE,
    MUGSHOT_CLAIR,
    MUGSHOT_LANCE,
    MUGSHOT_EUSINE,
    MUGSHOT_NURSE,
    MUGSHOT_CLERK,
    MUGSHOT_COUNT,
};

enum MugshotEmotes {
    EMOTE_NORMAL = 0,
    EMOTE_ALT,
    EMOTE_COUNT,
};

#endif // GUARD_CONSTANTS_FIELD_MUGSHOTS_H
