KitakamiWell_B1F_MapScripts::
	.byte 0


KitakamiWellFezandipiti::
# 4 "data/maps/KitakamiWell_B1F/scripts.pory"
	lock
# 5 "data/maps/KitakamiWell_B1F/scripts.pory"
	faceplayer
# 6 "data/maps/KitakamiWell_B1F/scripts.pory"
	settotemboost B_POSITION_OPPONENT_LEFT, 1, 1, 1, 1, 1, 0, 0
# 7 "data/maps/KitakamiWell_B1F/scripts.pory"
	legendaryencounter SPECIES_FEZANDIPITI, 55, LOCALID_FEZANDIPITI, FLAG_HIDE_FEZANDIPITI
# 8 "data/maps/KitakamiWell_B1F/scripts.pory"
	release
	end

