# 1 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 2 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F_MapScripts::
# 3 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.byte 0
# 4 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 5 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_EventScript_Sign1::
# 6 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	lock
# 7 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_4F4_Text_Studio2Sign, MSGBOX_SIGN
# 8 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	closemessage
# 9 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	release
# 10 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	end
# 11 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 12 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_EventScript_Sign2::
# 13 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	lock
# 14 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_4F4_Text_ProductionSign, MSGBOX_SIGN
# 15 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	closemessage
# 16 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	release
# 17 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	end
# 18 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 19 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodRaidoTower4_EventScript_Grunt28::
# 20 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_28 GoldenrodCity_RadioTower_4F4_Text_GruntF4Seen, GoldenrodCity_RadioTower_4F4_Text_GruntF4Beaten
# 21 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_4F4_Text_GruntF4After, MSGBOX_AUTOCLOSE
# 22 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	end
# 23 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 24 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodRaidoTower4_EventScript_Grunt9::
# 25 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_9 GoldenrodCity_RadioTower_4F4_Text_GruntM10Seen, GoldenrodCity_RadioTower_4F4_Text_GruntM10Beaten
# 26 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_4F4_Text_GruntM10After, MSGBOX_AUTOCLOSE
# 27 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	end
# 28 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 29 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodRaidoTower4_EventScript_Proton::
# 30 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	trainerbattle_single TRAINER_PROTON_2 GoldenrodCity_RadioTower_4F4_Text_Proton_Seen, GoldenrodCity_RadioTower_4F4_Text_Proton_Beaten
# 31 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_4F4_Text_Proton_After, MSGBOX_AUTOCLOSE
# 32 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	end
# 33 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 34 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 35 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_EventScript_Fisher::
# 36 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	lock
# 37 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	faceplayer
# 38 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_4F4_Text_Fisher, MSGBOX_DEFAULT
# 39 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	closemessage
# 40 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	release
# 41 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	end
# 42 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 43 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_EventScript_Scientist::
# 44 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	trainerbattle_single TRAINER_RICH GoldenrodCity_RadioTower_4F4_Text_ScientistRichSeen, GoldenrodCity_RadioTower_4F4_Text_ScientistRichBeaten
# 45 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_4F4_Text_ScientistRichAfter, MSGBOX_AUTOCLOSE
# 46 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	end
# 47 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 48 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 49 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_EventScript_Mary::
# 50 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	lock
# 51 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	faceplayer
# 52 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	goto_if_eq VAR_GOLDENROD_CITY_STATE, 6, GoldenrodCity_RadioTower_4F4_EventScript_Mary2
# 53 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	goto_if_eq VAR_GOLDENROD_CITY_STATE, 7, GoldenrodCity_RadioTower_4F4_EventScript_Mary2
# 54 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	goto_if_eq VAR_GOLDENROD_CITY_STATE, 8, GoldenrodCity_RadioTower_4F4_EventScript_Mary2
# 55 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	goto_if_eq VAR_GOLDENROD_CITY_STATE, 9, GoldenrodCity_RadioTower_4F4_EventScript_Mary2
# 56 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	goto_if_unset FLAG_GOT_MARY_BRIGHT_POWDER, RadioF4_Mary3
# 57 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_4F4_Text_DJMaryAfter, MSGBOX_DEFAULT
# 58 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	closemessage
# 59 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	release
# 60 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	end
# 61 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 62 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_EventScript_Mary2::
# 63 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_4F4_Text_DJMary, MSGBOX_DEFAULT
# 64 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	closemessage
# 65 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	release
# 66 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	end
# 67 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 68 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_EventScript_Meowth::
# 69 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	lock
# 70 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	faceplayer
# 71 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	waitse
# 72 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	playmoncry SPECIES_MEOWTH, CRY_MODE_NORMAL
# 73 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	msgbox GoldenrodCity_RadioTower_4F4_Text_Meowth, MSGBOX_DEFAULT
# 74 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	waitmoncry
# 75 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	release
# 76 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	end
# 77 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 78 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 79 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_Text_Proton_Seen:
# 80 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "Proton: Now wait just one second!\p"
# 81 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "Aren't you the one who got in our\n"
# 82 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "way at Slowpoke Well?\p"
# 83 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "I see... You're doing all this\n"
# 84 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "because you want to make me angry.\l"
# 85 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "Be careful!\p"
# 86 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "But since you seem to wish it, I'll\n"
# 87 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "show you the full extent of a Team\l"
# 88 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "Rocket Executive'S wrath!$"
# 89 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 90 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_Text_Proton_Beaten:
# 91 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "Phew...$"
# 92 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 93 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_Text_Proton_After:
# 94 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "Proton: You may have won this\n"
# 95 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "time... But all you did was make\p"
# 96 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "Team Rocket's wrath grow.$"
# 97 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 98 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_Text_Fisher:
# 99 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "I listened to the radio while I was\n"
# 100 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "at the Ruins.\p"
# 101 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "I heard a strange broadcast there.$"
# 102 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 103 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_Text_DJMary:
# 104 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "Mary: Why? Why do I have to suffer\n"
# 105 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "through this?\p"
# 106 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "Meowth, help me!$"
# 107 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 108 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_Text_DJMaryCleared:
# 109 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "Mary: Oh! You're my little savior!\p"
# 110 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "Will you take this as my thanks?$"
# 111 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 112 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_Text_DJMaryPinkBow:
# 113 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "Mary: It's good for dodging the\p"
# 114 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "enemy's attacks.$"
# 115 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 116 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_Text_DJMaryAfter:
# 117 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "Mary: Please tune into me on Prof.\n"
# 118 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "Oak'S Pokémon Talk show!$"
# 119 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 120 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_Text_Meowth:
# 121 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "Meowth: Meowth…$"
# 122 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 123 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_Text_GruntM10Seen:
# 124 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "You plan to rescue the Director?\p"
# 125 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "That won't be possible because I'm\n"
# 126 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "going to beat you!$"
# 127 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 128 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_Text_GruntM10Beaten:
# 129 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "No! Unbelievable!$"
# 130 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 131 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_Text_GruntM10After:
# 132 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "I don't believe it! I was beaten!$"
# 133 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 134 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_Text_ExecutiveM2Seen:
# 135 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "Stop! I'm known as the Team Rocket\n"
# 136 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "fortress!\p"
# 137 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "You're not taking another step!$"
# 138 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 139 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_Text_ExecutiveM2Beaten:
# 140 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "The fortress came down!$"
# 141 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 142 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_Text_ExecutiveM2After:
# 143 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "You've earned my respect, so here's\n"
# 144 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "some advice.\p"
# 145 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "It's not too late. You can still turn\n"
# 146 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "back.$"
# 147 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 148 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_Text_GruntF4Seen:
# 149 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "Don't I think Pokémon are cute?\p"
# 150 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "I'll think my Pokémon are cute--\p"
# 151 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "after they beat yours!$"
# 152 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 153 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_Text_GruntF4Beaten:
# 154 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "Oh, no! They're so useless!$"
# 155 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 156 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_Text_GruntF4After:
# 157 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "I love my beautiful self!\p"
# 158 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "Who cares about Pokémon?$"
# 159 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 160 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_Text_ScientistRichSeen:
# 161 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "Most excellent.\p"
# 162 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "This Radio Tower will fulfill our\n"
# 163 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "grand design.$"
# 164 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 165 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_Text_ScientistRichBeaten:
# 166 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "Hmmm…\p"
# 167 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "All grand plans come with snags.$"
# 168 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 169 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_Text_ScientistRichAfter:
# 170 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "Do you honestly believe you can stop\n"
# 171 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "Team Rocket?$"
# 172 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 173 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_Text_ProductionSign:
# 174 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "4F Production$"
# 175 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"

# 176 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
GoldenrodCity_RadioTower_4F4_Text_Studio2Sign:
# 177 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "4F Studio 2$"

RadioF4_Mary3::
# 181 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	msgbox RadioF4_Mary3_Text_0
# 183 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	closemessage
# 184 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	giveitem ITEM_BRIGHT_POWDER
# 185 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	goto_if_eq VAR_RESULT, FALSE, Common_EventScript_BagIsFull
# 186 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	msgbox RadioF4_Mary3_Text_1
# 188 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	closemessage
# 189 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	setflag FLAG_GOT_MARY_BRIGHT_POWDER
# 190 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	closemessage
# 191 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	release
	end


RadioF4_Mary3_Text_0:
# 181 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "Mary: Oh my little savior!\n"
	.string "Won't you take this as my thanks?$"

RadioF4_Mary3_Text_1:
# 186 "data/maps/GoldenrodCity_RadioTower_4F/scripts.pory"
	.string "It's good for dodging enemy attacks!\n"
	.string "My Meowth loves it!$"
