AcuityCavern_MapScripts::
	.byte 0


AcuityCavern_Uxie::
# 4 "data/maps/AcuityCavern/scripts.pory"
	lock
# 5 "data/maps/AcuityCavern/scripts.pory"
	faceplayer
# 6 "data/maps/AcuityCavern/scripts.pory"
	settotemboost B_POSITION_OPPONENT_LEFT, 1, 1, 1, 1, 1, 0, 0
# 7 "data/maps/AcuityCavern/scripts.pory"
	legendaryencounter SPECIES_UXIE, 50, LOCALID_ACUITY_UXIE, FLAG_HIDE_UXIE
# 8 "data/maps/AcuityCavern/scripts.pory"
	release
	end

