KitakamiBorder_MapScripts::
	.byte 0


KitakamiBorder_OldLady::
# 4 "data/maps/KitakamiBorder/scripts.pory"
	msgbox KitakamiBorder_OldLady_Text_0, MSGBOX_NPC
	return


KitakamiBorder_HikerBenny::
	return


KitakamiBorder_OldLady_Text_0:
# 4 "data/maps/KitakamiBorder/scripts.pory"
	.string "I often come here to watch the valley\n"
	.string "between here and Mt. Silver. It soothes\l"
	.string "my mind.$"
