Kitakami_Temple_Bedroom_MapScripts::
	.byte 0


KitakamiTempleBedroom_Expert::
# 4 "data/maps/Kitakami_Temple_Bedroom/scripts.pory"
	msgbox KitakamiTempleBedroom_Expert_Text_0, MSGBOX_NPC
	return


KitakamiTempleBedroom_BattleGirl::
# 12 "data/maps/Kitakami_Temple_Bedroom/scripts.pory"
	msgbox KitakamiTempleBedroom_BattleGirl_Text_0, MSGBOX_NPC
	return


KitakamiTempleBedroom_Expert_Text_0:
# 4 "data/maps/Kitakami_Temple_Bedroom/scripts.pory"
	.string "It is not uncommon for travellers to\n"
	.string "spend some time training with us.\p"
	.string "It helps keep traditions alive in\n"
	.string "hearts of the Youth.$"

KitakamiTempleBedroom_BattleGirl_Text_0:
# 12 "data/maps/Kitakami_Temple_Bedroom/scripts.pory"
	.string "Ugh...\p"
	.string "They make us wake up at the\n"
	.string "crack of dawn every day...\p"
	.string "We have to fetch water from the base\n"
	.string "of the mountains to wash ourselves...\p"
	.string "I'm so sleepy... Zzz....$"
