KitakamiRoad_House_MapScripts::
	.byte 0


KitakamiBorder_VictiniLady::
# 4 "data/maps/KitakamiRoad_House/scripts.pory"
	lock
# 5 "data/maps/KitakamiRoad_House/scripts.pory"
	faceplayer
# 6 "data/maps/KitakamiRoad_House/scripts.pory"
	msgbox KitakamiBorder_VictiniLady_Text_0
# 7 "data/maps/KitakamiRoad_House/scripts.pory"
	release
	end


KitakamiBorder_VictiniLady_Text_0:
# 6 "data/maps/KitakamiRoad_House/scripts.pory"
	.string "TODO Victini event$"
