AbandonedRocketHideoutBackroom_MapScripts::
	.byte 0


ARH_LaptopBackroom::
# 4 "data/maps/AbandonedRocketHideoutBackroom/scripts.pory"
	msgbox ARH_LaptopBackroom_Text_0, MSGBOX_NPC
	return


ARH_NotesBackroom::
# 14 "data/maps/AbandonedRocketHideoutBackroom/scripts.pory"
	msgbox ARH_NotesBackroom_Text_0, MSGBOX_SIGN
	return


ARH_Strangewall::
# 30 "data/maps/AbandonedRocketHideoutBackroom/scripts.pory"
	msgbox ARH_Strangewall_Text_0, MSGBOX_SIGN
	return


ARH_LaptopBackroom_Text_0:
# 4 "data/maps/AbandonedRocketHideoutBackroom/scripts.pory"
	.string "While the laptop no longer has power,\n"
	.string "there's a small post-it note under it.\p"
	.string "SUBJECT SHADOW L????\p"
	.string "The rest of the text has been drenched\n"
	.string "by what seems to be coffee stains.$"

ARH_NotesBackroom_Text_0:
# 14 "data/maps/AbandonedRocketHideoutBackroom/scripts.pory"
	.string "Log - Emotion Compression Studies\p"
	.string "By crystallizing energy found from a\n"
	.string "certain legendary Pokémon, we have\l"
	.string "managed to create containers for\l"
	.string "holding strong negative emotions. \p"
	.string "These can be used like magnets on\n"
	.string "creatures of high purity to invert\l"
	.string "their emotions to the opposite end.\p"
	.string "Further testing will be required to\n"
	.string "see the long term effects.$"

ARH_Strangewall_Text_0:
# 30 "data/maps/AbandonedRocketHideoutBackroom/scripts.pory"
	.string "Something about this wall feels off,\n"
	.string "but there's no visible keyholes or\l"
	.string "card readers.$"
