AbandonedRocketHideout_MapScripts::
	.byte 0


MfirstMeeting::
# 4 "data/maps/AbandonedRocketHideout/scripts.pory"
	msgbox MfirstMeeting_Text_0, MSGBOX_NPC
	return


ARH_Note1::
# 8 "data/maps/AbandonedRocketHideout/scripts.pory"
	msgbox ARH_Note1_Text_0, MSGBOX_SIGN
	return


ARH_MiddleDoor::
# 12 "data/maps/AbandonedRocketHideout/scripts.pory"
	msgbox ARH_MiddleDoor_Text_0, MSGBOX_SIGN
	return


ARH_RightDoor::
# 16 "data/maps/AbandonedRocketHideout/scripts.pory"
	msgbox ARH_MiddleDoor_Text_0, MSGBOX_SIGN
	return


ARH_Note2::
# 20 "data/maps/AbandonedRocketHideout/scripts.pory"
	msgbox ARH_Note1_Text_0, MSGBOX_SIGN
	return


ARH_Computer1::
# 24 "data/maps/AbandonedRocketHideout/scripts.pory"
	msgbox ARH_Computer1_Text_0, MSGBOX_SIGN
	return


ARH_BoxLeft::
# 28 "data/maps/AbandonedRocketHideout/scripts.pory"
	msgbox ARH_BoxLeft_Text_0, MSGBOX_SIGN
	return


ARH_BoxRight1::
# 32 "data/maps/AbandonedRocketHideout/scripts.pory"
	msgbox ARH_BoxLeft_Text_0, MSGBOX_SIGN
	return


ARH_BoxRight2::
# 36 "data/maps/AbandonedRocketHideout/scripts.pory"
	msgbox ARH_BoxLeft_Text_0, MSGBOX_SIGN
	return


ARH_BoxWrong::
# 40 "data/maps/AbandonedRocketHideout/scripts.pory"
	msgbox ARH_BoxWrong_Text_0, MSGBOX_SIGN
	return


ARH_MachineRight::
# 44 "data/maps/AbandonedRocketHideout/scripts.pory"
	msgbox ARH_MachineRight_Text_0, MSGBOX_SIGN
	return


MfirstMeeting_Text_0:
# 4 "data/maps/AbandonedRocketHideout/scripts.pory"
	.string "TODO; Shadow gem event$"

ARH_Note1_Text_0:
# 8 "data/maps/AbandonedRocketHideout/scripts.pory"
	.string "Todo notes$"

ARH_MiddleDoor_Text_0:
# 12 "data/maps/AbandonedRocketHideout/scripts.pory"
	.string "The door is locked.$"

ARH_Computer1_Text_0:
# 24 "data/maps/AbandonedRocketHideout/scripts.pory"
	.string "Todo computa$"

ARH_BoxLeft_Text_0:
# 28 "data/maps/AbandonedRocketHideout/scripts.pory"
	.string "Very interesting box.$"

ARH_BoxWrong_Text_0:
# 40 "data/maps/AbandonedRocketHideout/scripts.pory"
	.string "Not very interesting box.$"

ARH_MachineRight_Text_0:
# 44 "data/maps/AbandonedRocketHideout/scripts.pory"
	.string "A machine.$"
