VajraPyramidOutside_MapScripts::
	.byte 0


VajraPyramidOutside_Door::
# 4 "data/maps/VajraPyramidOutside/scripts.pory"
	msgbox VajraPyramidOutside_Door_Text_0, MSGBOX_SIGN
	return


VajraPyramidOutside_RuinManiac::
# 8 "data/maps/VajraPyramidOutside/scripts.pory"
	msgbox VajraPyramidOutside_RuinManiac_Text_0, MSGBOX_NPC
	return


VajraPyramidOutside_Door_Text_0:
# 4 "data/maps/VajraPyramidOutside/scripts.pory"
	.string "The door is sealed shut tightly.$"

VajraPyramidOutside_RuinManiac_Text_0:
# 8 "data/maps/VajraPyramidOutside/scripts.pory"
	.string "There's mystery here waiting to be\n"
	.string "uncovered! I can sense it!$"
