KitakamiMountainEnclave_MapScripts::
	.byte 0


KitakamiMountainEnclave_Ogerpon::
# 4 "data/maps/KitakamiMountainEnclave/scripts.pory"
	lock
# 5 "data/maps/KitakamiMountainEnclave/scripts.pory"
	faceplayer
# 6 "data/maps/KitakamiMountainEnclave/scripts.pory"
	settotemboost B_POSITION_OPPONENT_LEFT, 1, 1, 1, 1, 1, 0, 0
# 7 "data/maps/KitakamiMountainEnclave/scripts.pory"
	legendaryencounter SPECIES_OGERPON, 55, LOCALID_KITAKAMIMOUNTAIN_OGERPON, FLAG_HIDE_OGERPON
# 8 "data/maps/KitakamiMountainEnclave/scripts.pory"
	release
	end

