KitakamiMountainEnclave_MapScripts::
	.byte 0


KitakamiMountainEnclave_Ogerpon::
# 4 "data/maps/KitakamiMountainEnclave/scripts.pory"
	lock
# 5 "data/maps/KitakamiMountainEnclave/scripts.pory"
	faceplayer
# 6 "data/maps/KitakamiMountainEnclave/scripts.pory"
	bosslegendaryencounter SPECIES_OGERPON, 55, LOCALID_KITAKAMIMOUNTAIN_OGERPON, FLAG_HIDE_OGERPON, 4, SPECIES_NONE, 110, BOSS_PHASE_PROFILE_OGERPON
# 7 "data/maps/KitakamiMountainEnclave/scripts.pory"
	release
	end

