# 1 "data/maps/Route34_DayCare/scripts.pory"

# 2 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_MapScripts::
# 3 "data/maps/Route34_DayCare/scripts.pory"
	.byte 0
# 4 "data/maps/Route34_DayCare/scripts.pory"

# 5 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Bookshelf1::
# 6 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_Bookshelf1, MSGBOX_SIGN
# 7 "data/maps/Route34_DayCare/scripts.pory"
	end
# 8 "data/maps/Route34_DayCare/scripts.pory"

# 9 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Bookshelf2::
# 10 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_Bookshelf2, MSGBOX_SIGN
# 11 "data/maps/Route34_DayCare/scripts.pory"
	end
# 12 "data/maps/Route34_DayCare/scripts.pory"

# 13 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Bookshelf3::
# 14 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_Bookshelf3, MSGBOX_SIGN
# 15 "data/maps/Route34_DayCare/scripts.pory"
	end
# 16 "data/maps/Route34_DayCare/scripts.pory"

# 17 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Bookshelf4::
# 18 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_Bookshelf4, MSGBOX_SIGN
# 19 "data/maps/Route34_DayCare/scripts.pory"
	end
# 20 "data/maps/Route34_DayCare/scripts.pory"

# 21 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_Bookshelf1:
# 22 "data/maps/Route34_DayCare/scripts.pory"
	.string "A dictionary!\p"
# 23 "data/maps/Route34_DayCare/scripts.pory"
	.string "{PLAYER} opened the dictionary to\n"
# 24 "data/maps/Route34_DayCare/scripts.pory"
	.string "a random page.\p"
# 25 "data/maps/Route34_DayCare/scripts.pory"
	.string "'Babe'\n"
# 26 "data/maps/Route34_DayCare/scripts.pory"
	.string "A noun, meaning infant or baby.\p"
# 27 "data/maps/Route34_DayCare/scripts.pory"
	.string "{PLAYER} put away the dictionary.$"
# 28 "data/maps/Route34_DayCare/scripts.pory"

# 29 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_Bookshelf2:
# 30 "data/maps/Route34_DayCare/scripts.pory"
	.string "A book about Pokémon!\p"
# 31 "data/maps/Route34_DayCare/scripts.pory"
	.string "{PLAYER} flipped through\n"
# 32 "data/maps/Route34_DayCare/scripts.pory"
	.string "the book.\p"
# 33 "data/maps/Route34_DayCare/scripts.pory"
	.string "It must have the word\n"
# 34 "data/maps/Route34_DayCare/scripts.pory"
	.string "Pokémon written on every page.\p"
# 35 "data/maps/Route34_DayCare/scripts.pory"
	.string "{PLAYER} put away the book.$"
# 36 "data/maps/Route34_DayCare/scripts.pory"

# 37 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_Bookshelf3:
# 38 "data/maps/Route34_DayCare/scripts.pory"
	.string "A book of word assocations!\p"
# 39 "data/maps/Route34_DayCare/scripts.pory"
	.string "{PLAYER} flipped through\n"
# 40 "data/maps/Route34_DayCare/scripts.pory"
	.string "the book.\p"
# 41 "data/maps/Route34_DayCare/scripts.pory"
	.string "Pichu -> Cute\l"
# 42 "data/maps/Route34_DayCare/scripts.pory"
	.string "Cleffa -> Cute\l"
# 43 "data/maps/Route34_DayCare/scripts.pory"
	.string "Igglybuff -> Song\l"
# 44 "data/maps/Route34_DayCare/scripts.pory"
	.string "Tyrogue -> Fighting\l"
# 45 "data/maps/Route34_DayCare/scripts.pory"
	.string "Smoochum -> Ice\l"
# 46 "data/maps/Route34_DayCare/scripts.pory"
	.string "Elekid -> Electric\l"
# 47 "data/maps/Route34_DayCare/scripts.pory"
	.string "Magby -> Fire\p"
# 48 "data/maps/Route34_DayCare/scripts.pory"
	.string "{PLAYER} put away the book.$"
# 49 "data/maps/Route34_DayCare/scripts.pory"

# 50 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_Bookshelf4:
# 51 "data/maps/Route34_DayCare/scripts.pory"
	.string "A book of Pokémon natures!\p"
# 52 "data/maps/Route34_DayCare/scripts.pory"
	.string "{PLAYER} flipped through\n"
# 53 "data/maps/Route34_DayCare/scripts.pory"
	.string "the book.\p"
# 54 "data/maps/Route34_DayCare/scripts.pory"
	.string "Pichu -> Static\l"
# 55 "data/maps/Route34_DayCare/scripts.pory"
	.string "Cleffa -> Cute Charm\l"
# 56 "data/maps/Route34_DayCare/scripts.pory"
	.string "Igglybuff -> Cute Charm\l"
# 57 "data/maps/Route34_DayCare/scripts.pory"
	.string "Tyrogue -> Guts\l"
# 58 "data/maps/Route34_DayCare/scripts.pory"
	.string "Smoochum -> Oblivious\l"
# 59 "data/maps/Route34_DayCare/scripts.pory"
	.string "Elekid -> Static\l"
# 60 "data/maps/Route34_DayCare/scripts.pory"
	.string "Magby -> Flame Body\p"
# 61 "data/maps/Route34_DayCare/scripts.pory"
	.string "{PLAYER} put away the book.$"
# 62 "data/maps/Route34_DayCare/scripts.pory"

# 63 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_Clerk::
# 64 "data/maps/Route34_DayCare/scripts.pory"
	lock
# 65 "data/maps/Route34_DayCare/scripts.pory"
	faceplayer
# 66 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_set FLAG_RECEIVED_ODD_EGG, Route34_DayCare_EventScript_ClerkAfter
# 67 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_ClerkBefore, MSGBOX_DEFAULT
# 68 "data/maps/Route34_DayCare/scripts.pory"
	getpartysize
# 69 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, PARTY_SIZE, Route34_DayCare_EventScript_ClerkPartyFull
# 70 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_ClerkQuestion, MSGBOX_DEFAULT
# 71 "data/maps/Route34_DayCare/scripts.pory"
	closemessage
# 72 "data/maps/Route34_DayCare/scripts.pory"
	setvar VAR_0x8004, EASY_CHAT_TYPE_INTERVIEW
# 73 "data/maps/Route34_DayCare/scripts.pory"
	setvar VAR_0x8005, 0
# 74 "data/maps/Route34_DayCare/scripts.pory"
	call Common_ShowEasyChatScreen
# 75 "data/maps/Route34_DayCare/scripts.pory"
	lock
# 76 "data/maps/Route34_DayCare/scripts.pory"
	faceplayer
# 77 "data/maps/Route34_DayCare/scripts.pory"
	switch VAR_RESULT
# 78 "data/maps/Route34_DayCare/scripts.pory"
	case 0, Route34_DayCare_EventScript_ClerkRejection
# 79 "data/maps/Route34_DayCare/scripts.pory"
	case 1, Route34_DayCare_EventScript_GivePichu
# 80 "data/maps/Route34_DayCare/scripts.pory"
	case 2, Route34_DayCare_EventScript_GiveCleffa
# 81 "data/maps/Route34_DayCare/scripts.pory"
	case 3, Route34_DayCare_EventScript_GiveIgglybuff
# 82 "data/maps/Route34_DayCare/scripts.pory"
	case 4, Route34_DayCare_EventScript_GiveTyrogue
# 83 "data/maps/Route34_DayCare/scripts.pory"
	case 5, Route34_DayCare_EventScript_GiveSmoochum
# 84 "data/maps/Route34_DayCare/scripts.pory"
	case 6, Route34_DayCare_EventScript_GiveElekid
# 85 "data/maps/Route34_DayCare/scripts.pory"
	case 7, Route34_DayCare_EventScript_GiveMagby
# 86 "data/maps/Route34_DayCare/scripts.pory"
	closemessage
# 87 "data/maps/Route34_DayCare/scripts.pory"
	release
# 88 "data/maps/Route34_DayCare/scripts.pory"
	end
# 89 "data/maps/Route34_DayCare/scripts.pory"

# 90 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_GivePichu::
# 91 "data/maps/Route34_DayCare/scripts.pory"
	giveoddegg 1
# 92 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_Clerk_GaveEgg
# 93 "data/maps/Route34_DayCare/scripts.pory"

# 94 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_GiveCleffa::
# 95 "data/maps/Route34_DayCare/scripts.pory"
	giveoddegg 2
# 96 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_Clerk_GaveEgg
# 97 "data/maps/Route34_DayCare/scripts.pory"

# 98 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_GiveIgglybuff::
# 99 "data/maps/Route34_DayCare/scripts.pory"
	giveoddegg 3
# 100 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_Clerk_GaveEgg
# 101 "data/maps/Route34_DayCare/scripts.pory"

# 102 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_GiveTyrogue::
# 103 "data/maps/Route34_DayCare/scripts.pory"
	giveoddegg 4
# 104 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_Clerk_GaveEgg
# 105 "data/maps/Route34_DayCare/scripts.pory"

# 106 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_GiveSmoochum::
# 107 "data/maps/Route34_DayCare/scripts.pory"
	giveoddegg 5
# 108 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_Clerk_GaveEgg
# 109 "data/maps/Route34_DayCare/scripts.pory"

# 110 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_GiveElekid::
# 111 "data/maps/Route34_DayCare/scripts.pory"
	giveoddegg 6
# 112 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_Clerk_GaveEgg
# 113 "data/maps/Route34_DayCare/scripts.pory"

# 114 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_GiveMagby::
# 115 "data/maps/Route34_DayCare/scripts.pory"
	giveoddegg 7
# 116 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_Clerk_GaveEgg
# 117 "data/maps/Route34_DayCare/scripts.pory"

# 118 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_Clerk_GaveEgg::
# 119 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_TakeCare, MSGBOX_DEFAULT
# 120 "data/maps/Route34_DayCare/scripts.pory"
	closemessage
# 121 "data/maps/Route34_DayCare/scripts.pory"
	delay 30
# 122 "data/maps/Route34_DayCare/scripts.pory"
	setflag FLAG_RECEIVED_ODD_EGG
# 123 "data/maps/Route34_DayCare/scripts.pory"
	playfanfare MUS_OBTAIN_ITEM
# 124 "data/maps/Route34_DayCare/scripts.pory"
	message Route34_DayCare_Text_ReceivedOddEgg
# 125 "data/maps/Route34_DayCare/scripts.pory"
	waitfanfare
# 126 "data/maps/Route34_DayCare/scripts.pory"
	closemessage
# 127 "data/maps/Route34_DayCare/scripts.pory"
	release
# 128 "data/maps/Route34_DayCare/scripts.pory"
	end
# 129 "data/maps/Route34_DayCare/scripts.pory"

# 130 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_ClerkPartyFull::
# 131 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_ClerkNoRoom, MSGBOX_DEFAULT
# 132 "data/maps/Route34_DayCare/scripts.pory"
	closemessage
# 133 "data/maps/Route34_DayCare/scripts.pory"
	release
# 134 "data/maps/Route34_DayCare/scripts.pory"
	end
# 135 "data/maps/Route34_DayCare/scripts.pory"

# 136 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_ClerkRejection::
# 137 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_Rejection, MSGBOX_DEFAULT
# 138 "data/maps/Route34_DayCare/scripts.pory"
	closemessage
# 139 "data/maps/Route34_DayCare/scripts.pory"
	release
# 140 "data/maps/Route34_DayCare/scripts.pory"
	end
# 141 "data/maps/Route34_DayCare/scripts.pory"

# 142 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_ClerkAfter::
# 143 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_ClerkAfter, MSGBOX_DEFAULT
# 144 "data/maps/Route34_DayCare/scripts.pory"
	closemessage
# 145 "data/maps/Route34_DayCare/scripts.pory"
	release
# 146 "data/maps/Route34_DayCare/scripts.pory"
	end
# 147 "data/maps/Route34_DayCare/scripts.pory"

# 148 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_ClerkBefore:
# 149 "data/maps/Route34_DayCare/scripts.pory"
	.string "I'm the Daycare couple's son.\p"
# 150 "data/maps/Route34_DayCare/scripts.pory"
	.string "An Odd Egg was found with a trainer's\n"
# 151 "data/maps/Route34_DayCare/scripts.pory"
	.string "Pokémon, but they didn't want it...\p"
# 152 "data/maps/Route34_DayCare/scripts.pory"
	.string "I'd offer it to you...\n"
# 153 "data/maps/Route34_DayCare/scripts.pory"
	.string "But how can I know you'll take good\l"
# 154 "data/maps/Route34_DayCare/scripts.pory"
	.string "care of it?$"
# 155 "data/maps/Route34_DayCare/scripts.pory"

# 156 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_ClerkNoRoom:
# 157 "data/maps/Route34_DayCare/scripts.pory"
	.string "It looks like you can't carry another\n"
# 158 "data/maps/Route34_DayCare/scripts.pory"
	.string "Pokémon anyway.$"
# 159 "data/maps/Route34_DayCare/scripts.pory"

# 160 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_ClerkQuestion:
# 161 "data/maps/Route34_DayCare/scripts.pory"
	.string "Answer this question for me.\n"
# 162 "data/maps/Route34_DayCare/scripts.pory"
	.string "How do you feel about this Odd Egg?$"
# 163 "data/maps/Route34_DayCare/scripts.pory"

# 164 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_Rejection:
# 165 "data/maps/Route34_DayCare/scripts.pory"
	.string "Hmm, I think this egg isn't for you.\p"
# 166 "data/maps/Route34_DayCare/scripts.pory"
	.string "It would be irresponsible of me to\n"
# 167 "data/maps/Route34_DayCare/scripts.pory"
	.string "give out a precious Egg like this\l"
# 168 "data/maps/Route34_DayCare/scripts.pory"
	.string "to someone who isn't as well-read\l"
# 169 "data/maps/Route34_DayCare/scripts.pory"
	.string "on the subject of Pokémon breeding!$"
# 170 "data/maps/Route34_DayCare/scripts.pory"

# 171 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_ReceivedOddEgg:
# 172 "data/maps/Route34_DayCare/scripts.pory"
	.string "{PLAYER} Received the Odd Egg.$"
# 173 "data/maps/Route34_DayCare/scripts.pory"

# 174 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_TakeCare:
# 175 "data/maps/Route34_DayCare/scripts.pory"
	.string "I knew you were the right trainer\n"
# 176 "data/maps/Route34_DayCare/scripts.pory"
	.string "for the job. Take good care of it!$"
# 177 "data/maps/Route34_DayCare/scripts.pory"

# 178 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_ClerkAfter:
# 179 "data/maps/Route34_DayCare/scripts.pory"
	.string "We see a lot of those eggs around\n"
# 180 "data/maps/Route34_DayCare/scripts.pory"
	.string "here.\p"
# 181 "data/maps/Route34_DayCare/scripts.pory"
	.string "Something was different about that\n"
# 182 "data/maps/Route34_DayCare/scripts.pory"
	.string "one, though.$"
# 183 "data/maps/Route34_DayCare/scripts.pory"

# 184 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_Ditto::
# 185 "data/maps/Route34_DayCare/scripts.pory"
	lock
# 186 "data/maps/Route34_DayCare/scripts.pory"
	faceplayer
# 187 "data/maps/Route34_DayCare/scripts.pory"
	waitse
# 188 "data/maps/Route34_DayCare/scripts.pory"
	playmoncry SPECIES_DITTO, CRY_MODE_NORMAL
# 189 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_Ditto, MSGBOX_DEFAULT
# 190 "data/maps/Route34_DayCare/scripts.pory"
	waitmoncry
# 191 "data/maps/Route34_DayCare/scripts.pory"
	release
# 192 "data/maps/Route34_DayCare/scripts.pory"
	end
# 193 "data/maps/Route34_DayCare/scripts.pory"

# 194 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_Ditto:
# 195 "data/maps/Route34_DayCare/scripts.pory"
	.string "Ditto: Tto!$"
# 196 "data/maps/Route34_DayCare/scripts.pory"

# 197 "data/maps/Route34_DayCare/scripts.pory"
Route34_EventScript_DaycareMan::
# 198 "data/maps/Route34_DayCare/scripts.pory"
	lock
# 199 "data/maps/Route34_DayCare/scripts.pory"
	faceplayer
# 200 "data/maps/Route34_DayCare/scripts.pory"
	special GetDaycareMonNicknames
# 201 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, GetDaycareState
# 202 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, DAYCARE_EGG_WAITING, Route34_EventScript_DaycareEggWaiting
# 203 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, DAYCARE_ONE_MON, Route34_EventScript_CheckOnOneMon
# 204 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, DAYCARE_TWO_MONS, Route34_EventScript_CheckOnTwoMons
# 205 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_Text_SeeWifeIfYoudLikeMeToRaiseMon, MSGBOX_DEFAULT
# 206 "data/maps/Route34_DayCare/scripts.pory"
	release
# 207 "data/maps/Route34_DayCare/scripts.pory"
	end
# 208 "data/maps/Route34_DayCare/scripts.pory"

# 209 "data/maps/Route34_DayCare/scripts.pory"
Route34_EventScript_DaycareEggWaiting::
# 210 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_Text_DoYouWantEgg, MSGBOX_YESNO
# 211 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, YES, Route34_EventScript_DaycareAcceptEgg
# 212 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_Text_IWillKeepDoYouWantIt, MSGBOX_YESNO
# 213 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, YES, Route34_EventScript_DaycareAcceptEgg
# 214 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_Text_IllKeepIt, MSGBOX_DEFAULT
# 215 "data/maps/Route34_DayCare/scripts.pory"
	clearflag FLAG_PENDING_DAYCARE_EGG
# 216 "data/maps/Route34_DayCare/scripts.pory"
	special RejectEggFromDayCare
# 217 "data/maps/Route34_DayCare/scripts.pory"
	release
# 218 "data/maps/Route34_DayCare/scripts.pory"
	end
# 219 "data/maps/Route34_DayCare/scripts.pory"

# 220 "data/maps/Route34_DayCare/scripts.pory"
Route34_EventScript_DaycareAcceptEgg::
# 221 "data/maps/Route34_DayCare/scripts.pory"
	@specialvar VAR_0x8004, GetMaxPartySize @ tx_randomizer_and_challenges
# 222 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, CalculatePlayerPartyCount
# 223 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_ne VAR_RESULT, VAR_0x8004, Route34_EventScript_DaycareReceiveEgg
# 224 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_Text_YouHaveNoRoomForIt, MSGBOX_DEFAULT
# 225 "data/maps/Route34_DayCare/scripts.pory"
	release
# 226 "data/maps/Route34_DayCare/scripts.pory"
	end
# 227 "data/maps/Route34_DayCare/scripts.pory"

# 228 "data/maps/Route34_DayCare/scripts.pory"
Route34_EventScript_DaycareReceiveEgg::
# 229 "data/maps/Route34_DayCare/scripts.pory"
	message Route34_Text_ReceivedEgg
# 230 "data/maps/Route34_DayCare/scripts.pory"
	playfanfare MUS_LEVEL_UP
# 231 "data/maps/Route34_DayCare/scripts.pory"
	waitfanfare
# 232 "data/maps/Route34_DayCare/scripts.pory"
	waitbuttonpress
# 233 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_Text_TakeGoodCareOfIt, MSGBOX_DEFAULT
# 234 "data/maps/Route34_DayCare/scripts.pory"
	special GiveEggFromDaycare
# 235 "data/maps/Route34_DayCare/scripts.pory"
	clearflag FLAG_PENDING_DAYCARE_EGG
# 236 "data/maps/Route34_DayCare/scripts.pory"
	release
# 237 "data/maps/Route34_DayCare/scripts.pory"
	end
# 238 "data/maps/Route34_DayCare/scripts.pory"

# 239 "data/maps/Route34_DayCare/scripts.pory"
Route34_EventScript_CheckMonReceivedMail::
# 240 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, CheckDaycareMonReceivedMail
# 241 "data/maps/Route34_DayCare/scripts.pory"
	call_if_eq VAR_RESULT, 1, Route34_EventScript_MonReceivedMail
# 242 "data/maps/Route34_DayCare/scripts.pory"
	return
# 243 "data/maps/Route34_DayCare/scripts.pory"

# 244 "data/maps/Route34_DayCare/scripts.pory"
Route34_EventScript_MonReceivedMail::
# 245 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_Text_FriendlyWithOtherTrainersMon, MSGBOX_DEFAULT
# 246 "data/maps/Route34_DayCare/scripts.pory"
	return
# 247 "data/maps/Route34_DayCare/scripts.pory"

# 248 "data/maps/Route34_DayCare/scripts.pory"
Route34_EventScript_CheckOnOneMon::
# 249 "data/maps/Route34_DayCare/scripts.pory"
	special GetDaycareMonNicknames
# 250 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_Text_YourMonIsDoingFine, MSGBOX_DEFAULT
# 251 "data/maps/Route34_DayCare/scripts.pory"
	setvar VAR_0x8004, 0
# 252 "data/maps/Route34_DayCare/scripts.pory"
	call Route34_EventScript_CheckMonReceivedMail
# 253 "data/maps/Route34_DayCare/scripts.pory"
	release
# 254 "data/maps/Route34_DayCare/scripts.pory"
	end
# 255 "data/maps/Route34_DayCare/scripts.pory"

# 256 "data/maps/Route34_DayCare/scripts.pory"
Route34_EventScript_CheckOnTwoMons::
# 257 "data/maps/Route34_DayCare/scripts.pory"
	special GetDaycareMonNicknames
# 258 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_Text_YourMonsAreDoingFine, MSGBOX_DEFAULT
# 259 "data/maps/Route34_DayCare/scripts.pory"
	special SetDaycareCompatibilityString
# 260 "data/maps/Route34_DayCare/scripts.pory"
	special ShowFieldMessageStringVar4
# 261 "data/maps/Route34_DayCare/scripts.pory"
	waitmessage
# 262 "data/maps/Route34_DayCare/scripts.pory"
	waitbuttonpress
# 263 "data/maps/Route34_DayCare/scripts.pory"
	setvar VAR_0x8004, 0
# 264 "data/maps/Route34_DayCare/scripts.pory"
	call Route34_EventScript_CheckMonReceivedMail
# 265 "data/maps/Route34_DayCare/scripts.pory"
	setvar VAR_0x8004, 1
# 266 "data/maps/Route34_DayCare/scripts.pory"
	call Route34_EventScript_CheckMonReceivedMail
# 267 "data/maps/Route34_DayCare/scripts.pory"
	release
# 268 "data/maps/Route34_DayCare/scripts.pory"
	end
# 269 "data/maps/Route34_DayCare/scripts.pory"

# 270 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_DaycareWoman::
# 271 "data/maps/Route34_DayCare/scripts.pory"
	lock
# 272 "data/maps/Route34_DayCare/scripts.pory"
	faceplayer
# 273 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, GetDaycareState
# 274 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, DAYCARE_EGG_WAITING, Route34_DayCare_EventScript_EggWaiting
# 275 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, DAYCARE_ONE_MON, Route34_DayCare_EventScript_OneMonInDaycare
# 276 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, DAYCARE_TWO_MONS, Route34_DayCare_EventScript_TwoMonsInDaycare
# 277 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_WouldYouLikeUsToRaiseAMon, MSGBOX_YESNO
# 278 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, YES, Route34_DayCare_EventScript_GiveMonToRaise
# 279 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_FineThenComeAgain, MSGBOX_DEFAULT
# 280 "data/maps/Route34_DayCare/scripts.pory"
	release
# 281 "data/maps/Route34_DayCare/scripts.pory"
	end
# 282 "data/maps/Route34_DayCare/scripts.pory"

# 283 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_GiveMonToRaise::
# 284 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, CountPartyNonEggMons
# 285 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, 1, Route34_DayCare_EventScript_OnlyOneMon
# 286 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, CountPartyAliveNonEggMons
# 287 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, 2, Route34_DayCare_EventScript_OnlyTwoAliveMons
# 288 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_WhichMonShouldWeRaise, MSGBOX_DEFAULT
# 289 "data/maps/Route34_DayCare/scripts.pory"
	fadescreen FADE_TO_BLACK
# 290 "data/maps/Route34_DayCare/scripts.pory"
	special ChooseSendDaycareMon
# 291 "data/maps/Route34_DayCare/scripts.pory"
	waitstate
# 292 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_0x8004, PARTY_NOTHING_CHOSEN, Route34_DayCare_EventScript_ComeAgain
# 293 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, CountPartyAliveNonEggMons_IgnoreVar0x8004Slot
# 294 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, 0, Route34_DayCare_EventScript_OnlyOneAliveMon
# 295 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_0x8005, GetSelectedMonNicknameAndSpecies
# 296 "data/maps/Route34_DayCare/scripts.pory"
	waitse
# 297 "data/maps/Route34_DayCare/scripts.pory"
	playmoncry VAR_0x8005, CRY_MODE_NORMAL
# 298 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_WellRaiseYourMon, MSGBOX_DEFAULT
# 299 "data/maps/Route34_DayCare/scripts.pory"
	waitmoncry
# 300 "data/maps/Route34_DayCare/scripts.pory"
	special StoreSelectedPokemonInDaycare
# 301 "data/maps/Route34_DayCare/scripts.pory"
	callnative UpdateFollowingPokemon
# 302 "data/maps/Route34_DayCare/scripts.pory"
	incrementgamestat GAME_STAT_USED_DAYCARE
# 303 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, GetDaycareState
# 304 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, DAYCARE_ONE_MON, Route34_DayCare_EventScript_CanRaiseOneMore
# 305 "data/maps/Route34_DayCare/scripts.pory"
	release
# 306 "data/maps/Route34_DayCare/scripts.pory"
	end
# 307 "data/maps/Route34_DayCare/scripts.pory"

# 308 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_ComeAgain::
# 309 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_ComeAgain, MSGBOX_DEFAULT
# 310 "data/maps/Route34_DayCare/scripts.pory"
	release
# 311 "data/maps/Route34_DayCare/scripts.pory"
	end
# 312 "data/maps/Route34_DayCare/scripts.pory"

# 313 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_CanRaiseOneMore::
# 314 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_WeCanRaiseOneMore, MSGBOX_YESNO
# 315 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, YES, Route34_DayCare_EventScript_GiveMonToRaise
# 316 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_ComeAgain
# 317 "data/maps/Route34_DayCare/scripts.pory"
	end
# 318 "data/maps/Route34_DayCare/scripts.pory"

# 319 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_OnlyOneMon::
# 320 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_YouHaveJustOneMon, MSGBOX_DEFAULT
# 321 "data/maps/Route34_DayCare/scripts.pory"
	release
# 322 "data/maps/Route34_DayCare/scripts.pory"
	end
# 323 "data/maps/Route34_DayCare/scripts.pory"

# 324 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_OnlyOneAliveMon::
# 325 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_WhatWillYouBattleWith, MSGBOX_DEFAULT
# 326 "data/maps/Route34_DayCare/scripts.pory"
	release
# 327 "data/maps/Route34_DayCare/scripts.pory"
	end
# 328 "data/maps/Route34_DayCare/scripts.pory"

# 329 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_OnlyTwoAliveMons::
# 330 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_YoullBeLeftWithJustOne, MSGBOX_DEFAULT
# 331 "data/maps/Route34_DayCare/scripts.pory"
	release
# 332 "data/maps/Route34_DayCare/scripts.pory"
	end
# 333 "data/maps/Route34_DayCare/scripts.pory"

# 334 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_EggWaiting::
# 335 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_HusbandWasLookingForYou, MSGBOX_DEFAULT
# 336 "data/maps/Route34_DayCare/scripts.pory"
	release
# 337 "data/maps/Route34_DayCare/scripts.pory"
	end
# 338 "data/maps/Route34_DayCare/scripts.pory"

# 339 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_YourMonHasGrownXLevels::
# 340 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_YourMonHasGrownXLevels, MSGBOX_DEFAULT
# 341 "data/maps/Route34_DayCare/scripts.pory"
	return
# 342 "data/maps/Route34_DayCare/scripts.pory"

# 343 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_DisplayLevelsGained::
# 344 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, GetNumLevelsGainedFromDaycare
# 345 "data/maps/Route34_DayCare/scripts.pory"
	call_if_ne VAR_RESULT, 0, Route34_DayCare_EventScript_YourMonHasGrownXLevels
# 346 "data/maps/Route34_DayCare/scripts.pory"
	return
# 347 "data/maps/Route34_DayCare/scripts.pory"

# 348 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_OneMonInDaycare::
# 349 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_GoodToSeeYou, MSGBOX_DEFAULT
# 350 "data/maps/Route34_DayCare/scripts.pory"
	setvar VAR_0x8004, 0
# 351 "data/maps/Route34_DayCare/scripts.pory"
	call Route34_DayCare_EventScript_DisplayLevelsGained
# 352 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_WeCanRaiseOneMore, MSGBOX_YESNO
# 353 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, YES, Route34_DayCare_EventScript_GiveMonToRaise
# 354 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_TakeYourMonBack, MSGBOX_YESNO
# 355 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, YES, Route34_DayCare_EventScript_TryRetrieveMon
# 356 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_ComeAgain
# 357 "data/maps/Route34_DayCare/scripts.pory"
	end
# 358 "data/maps/Route34_DayCare/scripts.pory"

# 359 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_TryRetrieveMon::
# 360 "data/maps/Route34_DayCare/scripts.pory"
	@specialvar VAR_0x8004, GetMaxPartySize @ tx_randomizer_and_challenges
# 361 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, CalculatePlayerPartyCount
# 362 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, VAR_0x8004, Route34_DayCare_EventScript_NoRoom
# 363 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, GetDaycareState
# 364 "data/maps/Route34_DayCare/scripts.pory"
	setvar VAR_0x8004, 0
# 365 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, DAYCARE_ONE_MON, Route34_DayCare_EventScript_CostPrompt
# 366 "data/maps/Route34_DayCare/scripts.pory"
	special ShowDaycareLevelMenu
# 367 "data/maps/Route34_DayCare/scripts.pory"
	waitstate
# 368 "data/maps/Route34_DayCare/scripts.pory"
	copyvar VAR_0x8004, VAR_RESULT
# 369 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, DAYCARE_EXITED_LEVEL_MENU, Route34_DayCare_EventScript_ComeAgain
# 370 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_CostPrompt
# 371 "data/maps/Route34_DayCare/scripts.pory"
	end
# 372 "data/maps/Route34_DayCare/scripts.pory"

# 373 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_CostPrompt::
# 374 "data/maps/Route34_DayCare/scripts.pory"
	special GetDaycareCost
# 375 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_ItWillCostX, MSGBOX_YESNO
# 376 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, YES, Route34_DayCare_EventScript_CheckEnoughMoney
# 377 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_ComeAgain
# 378 "data/maps/Route34_DayCare/scripts.pory"
	end
# 379 "data/maps/Route34_DayCare/scripts.pory"

# 380 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_CheckEnoughMoney::
# 381 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, IsEnoughForCostInVar0x8005
# 382 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, 1, Route34_DayCare_EventScript_RetrieveMon
# 383 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_NotEnoughMoney, MSGBOX_DEFAULT
# 384 "data/maps/Route34_DayCare/scripts.pory"
	release
# 385 "data/maps/Route34_DayCare/scripts.pory"
	end
# 386 "data/maps/Route34_DayCare/scripts.pory"

# 387 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_RetrieveMon::
# 388 "data/maps/Route34_DayCare/scripts.pory"
	@applymovement LOCALID_DAYCARE_LADY, Route34_DayCare_Movement_RetrieveDaycareMon
# 389 "data/maps/Route34_DayCare/scripts.pory"
	@waitmovement 0
# 390 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, TakePokemonFromDaycare
# 391 "data/maps/Route34_DayCare/scripts.pory"
	special SubtractMoneyFromVar0x8005
# 392 "data/maps/Route34_DayCare/scripts.pory"
	playse SE_SHOP
# 393 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_HeresYourMon, MSGBOX_DEFAULT
# 394 "data/maps/Route34_DayCare/scripts.pory"
	waitse
# 395 "data/maps/Route34_DayCare/scripts.pory"
	playmoncry VAR_RESULT, CRY_MODE_NORMAL
# 396 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_TookBackMon, MSGBOX_DEFAULT
# 397 "data/maps/Route34_DayCare/scripts.pory"
	waitmoncry
# 398 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, GetDaycareState
# 399 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, DAYCARE_ONE_MON, Route34_DayCare_EventScript_AskRetrieveOtherMon
# 400 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_ComeAgain
# 401 "data/maps/Route34_DayCare/scripts.pory"
	end
# 402 "data/maps/Route34_DayCare/scripts.pory"

# 403 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_AskRetrieveOtherMon::
# 404 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_TakeOtherOneBackToo, MSGBOX_YESNO
# 405 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, YES, Route34_DayCare_EventScript_TryRetrieveMon
# 406 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_ComeAgain
# 407 "data/maps/Route34_DayCare/scripts.pory"
	end
# 408 "data/maps/Route34_DayCare/scripts.pory"

# 409 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_NoRoom::
# 410 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_YourTeamIsFull, MSGBOX_DEFAULT
# 411 "data/maps/Route34_DayCare/scripts.pory"
	release
# 412 "data/maps/Route34_DayCare/scripts.pory"
	end
# 413 "data/maps/Route34_DayCare/scripts.pory"

# 414 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Movement_RetrieveDaycareMon:
# 415 "data/maps/Route34_DayCare/scripts.pory"
	delay_16
# 416 "data/maps/Route34_DayCare/scripts.pory"
	delay_16
# 417 "data/maps/Route34_DayCare/scripts.pory"
	face_left
# 418 "data/maps/Route34_DayCare/scripts.pory"
	delay_16
# 419 "data/maps/Route34_DayCare/scripts.pory"
	delay_16
# 420 "data/maps/Route34_DayCare/scripts.pory"
	face_right
# 421 "data/maps/Route34_DayCare/scripts.pory"
	delay_16
# 422 "data/maps/Route34_DayCare/scripts.pory"
	delay_16
# 423 "data/maps/Route34_DayCare/scripts.pory"
	face_up
# 424 "data/maps/Route34_DayCare/scripts.pory"
	walk_slow_up
# 425 "data/maps/Route34_DayCare/scripts.pory"
	set_invisible
# 426 "data/maps/Route34_DayCare/scripts.pory"
	delay_16
# 427 "data/maps/Route34_DayCare/scripts.pory"
	delay_16
# 428 "data/maps/Route34_DayCare/scripts.pory"
	delay_16
# 429 "data/maps/Route34_DayCare/scripts.pory"
	delay_16
# 430 "data/maps/Route34_DayCare/scripts.pory"
	delay_16
# 431 "data/maps/Route34_DayCare/scripts.pory"
	face_down
# 432 "data/maps/Route34_DayCare/scripts.pory"
	set_visible
# 433 "data/maps/Route34_DayCare/scripts.pory"
	walk_slow_down
# 434 "data/maps/Route34_DayCare/scripts.pory"
	step_end
# 435 "data/maps/Route34_DayCare/scripts.pory"

# 436 "data/maps/Route34_DayCare/scripts.pory"
@ Unused. Possibly a commented script, or a typo end added to the above Movement script
# 437 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_UnusedEnd::
# 438 "data/maps/Route34_DayCare/scripts.pory"
	end
# 439 "data/maps/Route34_DayCare/scripts.pory"

# 440 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_TwoMonsInDaycare::
# 441 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_GoodToSeeYou, MSGBOX_DEFAULT
# 442 "data/maps/Route34_DayCare/scripts.pory"
	setvar VAR_0x8004, 0
# 443 "data/maps/Route34_DayCare/scripts.pory"
	call Route34_DayCare_EventScript_DisplayLevelsGained
# 444 "data/maps/Route34_DayCare/scripts.pory"
	setvar VAR_0x8004, 1
# 445 "data/maps/Route34_DayCare/scripts.pory"
	call Route34_DayCare_EventScript_DisplayLevelsGained
# 446 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_TakeYourMonBack, MSGBOX_YESNO
# 447 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, YES, Route34_DayCare_EventScript_TryRetrieveMon
# 448 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_ComeAgain, MSGBOX_DEFAULT
# 449 "data/maps/Route34_DayCare/scripts.pory"
	release
# 450 "data/maps/Route34_DayCare/scripts.pory"
	end
# 451 "data/maps/Route34_DayCare/scripts.pory"

# 452 "data/maps/Route34_DayCare/scripts.pory"
Route34_Text_SeeWifeIfYoudLikeMeToRaiseMon:
# 453 "data/maps/Route34_DayCare/scripts.pory"
	.string "I'm the Day-Care Man.\p"
# 454 "data/maps/Route34_DayCare/scripts.pory"
	.string "I help take care of the precious\n"
# 455 "data/maps/Route34_DayCare/scripts.pory"
	.string "Pokémon of Trainers.\p"
# 456 "data/maps/Route34_DayCare/scripts.pory"
	.string "If you'd like me to raise your Pokémon,\n"
# 457 "data/maps/Route34_DayCare/scripts.pory"
	.string "have a word with my wife.$"
# 458 "data/maps/Route34_DayCare/scripts.pory"

# 459 "data/maps/Route34_DayCare/scripts.pory"
Route34_Text_DoYouWantEgg:
# 460 "data/maps/Route34_DayCare/scripts.pory"
	.string "Ah, it's you!\p"
# 461 "data/maps/Route34_DayCare/scripts.pory"
	.string "We were raising your Pokémon,\n"
# 462 "data/maps/Route34_DayCare/scripts.pory"
	.string "and my goodness, were we surprised!\p"
# 463 "data/maps/Route34_DayCare/scripts.pory"
	.string "Your Pokémon had an Egg!\p"
# 464 "data/maps/Route34_DayCare/scripts.pory"
	.string "We don't know how it got there,\n"
# 465 "data/maps/Route34_DayCare/scripts.pory"
	.string "but your Pokémon had it.\p"
# 466 "data/maps/Route34_DayCare/scripts.pory"
	.string "You do want it, yes?$"
# 467 "data/maps/Route34_DayCare/scripts.pory"

# 468 "data/maps/Route34_DayCare/scripts.pory"
Route34_Text_YourMonIsDoingFine:
# 469 "data/maps/Route34_DayCare/scripts.pory"
	.string "Ah, it's you! Good to see you.\n"
# 470 "data/maps/Route34_DayCare/scripts.pory"
	.string "Your {STR_VAR_1}'s doing fine.$"
# 471 "data/maps/Route34_DayCare/scripts.pory"

# 472 "data/maps/Route34_DayCare/scripts.pory"
Route34_Text_IllKeepIt:
# 473 "data/maps/Route34_DayCare/scripts.pory"
	.string "Well then, I'll keep it.\n"
# 474 "data/maps/Route34_DayCare/scripts.pory"
	.string "Thanks!$"
# 475 "data/maps/Route34_DayCare/scripts.pory"

# 476 "data/maps/Route34_DayCare/scripts.pory"
Route34_Text_YouHaveNoRoomForIt:
# 477 "data/maps/Route34_DayCare/scripts.pory"
	.string "You have no room for it…\n"
# 478 "data/maps/Route34_DayCare/scripts.pory"
	.string "Come back when you've made room.$"
# 479 "data/maps/Route34_DayCare/scripts.pory"

# 480 "data/maps/Route34_DayCare/scripts.pory"
Route34_Text_ReceivedEgg:
# 481 "data/maps/Route34_DayCare/scripts.pory"
	.string "{PLAYER} received the Egg from\n"
# 482 "data/maps/Route34_DayCare/scripts.pory"
	.string "the Day-Care Man.$"
# 483 "data/maps/Route34_DayCare/scripts.pory"

# 484 "data/maps/Route34_DayCare/scripts.pory"
Route34_Text_TakeGoodCareOfIt:
# 485 "data/maps/Route34_DayCare/scripts.pory"
	.string "Take good care of it.$"
# 486 "data/maps/Route34_DayCare/scripts.pory"

# 487 "data/maps/Route34_DayCare/scripts.pory"
Route34_Text_FriendlyWithOtherTrainersMon:
# 488 "data/maps/Route34_DayCare/scripts.pory"
	.string "By the way, about your {STR_VAR_1},\n"
# 489 "data/maps/Route34_DayCare/scripts.pory"
	.string "it seemed to be friendly with\l"
# 490 "data/maps/Route34_DayCare/scripts.pory"
	.string "{STR_VAR_2}'s {STR_VAR_3}.\p"
# 491 "data/maps/Route34_DayCare/scripts.pory"
	.string "I may even have seen it receiving\n"
# 492 "data/maps/Route34_DayCare/scripts.pory"
	.string "a piece of Mail.$"
# 493 "data/maps/Route34_DayCare/scripts.pory"

# 494 "data/maps/Route34_DayCare/scripts.pory"
@ Unused
# 495 "data/maps/Route34_DayCare/scripts.pory"
Route34_Text_SeeWifeIfYouWantToPickUpMon:
# 496 "data/maps/Route34_DayCare/scripts.pory"
	.string "If you want to pick up your Pokémon,\n"
# 497 "data/maps/Route34_DayCare/scripts.pory"
	.string "have a word with my wife.$"
# 498 "data/maps/Route34_DayCare/scripts.pory"

# 499 "data/maps/Route34_DayCare/scripts.pory"
Route34_Text_YourMonsAreDoingFine:
# 500 "data/maps/Route34_DayCare/scripts.pory"
	.string "Ah, it's you! Your {STR_VAR_1} and\n"
# 501 "data/maps/Route34_DayCare/scripts.pory"
	.string "{STR_VAR_2} are doing fine.$"
# 502 "data/maps/Route34_DayCare/scripts.pory"

# 503 "data/maps/Route34_DayCare/scripts.pory"
Route34_Text_IWillKeepDoYouWantIt:
# 504 "data/maps/Route34_DayCare/scripts.pory"
	.string "I really will keep it.\n"
# 505 "data/maps/Route34_DayCare/scripts.pory"
	.string "You do want this, yes?$"
# 506 "data/maps/Route34_DayCare/scripts.pory"

# 507 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_WouldYouLikeUsToRaiseAMon:
# 508 "data/maps/Route34_DayCare/scripts.pory"
	.string "I'm the Day-Care Lady.\p"
# 509 "data/maps/Route34_DayCare/scripts.pory"
	.string "We can raise Pokémon for you.\p"
# 510 "data/maps/Route34_DayCare/scripts.pory"
	.string "Would you like us to raise one?$"
# 511 "data/maps/Route34_DayCare/scripts.pory"

# 512 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_WhichMonShouldWeRaise:
# 513 "data/maps/Route34_DayCare/scripts.pory"
	.string "Which Pokémon should we raise for\n"
# 514 "data/maps/Route34_DayCare/scripts.pory"
	.string "you?$"
# 515 "data/maps/Route34_DayCare/scripts.pory"

# 516 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_WellRaiseYourMon:
# 517 "data/maps/Route34_DayCare/scripts.pory"
	.string "Fine, we'll raise your {STR_VAR_1}\n"
# 518 "data/maps/Route34_DayCare/scripts.pory"
	.string "for a while.\p"
# 519 "data/maps/Route34_DayCare/scripts.pory"
	.string "Come back for it later.$"
# 520 "data/maps/Route34_DayCare/scripts.pory"

# 521 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_WeCanRaiseOneMore:
# 522 "data/maps/Route34_DayCare/scripts.pory"
	.string "We can raise two of your Pokémon.\n"
# 523 "data/maps/Route34_DayCare/scripts.pory"
	.string "Would you like us to raise one more?$"
# 524 "data/maps/Route34_DayCare/scripts.pory"

# 525 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_HusbandWasLookingForYou:
# 526 "data/maps/Route34_DayCare/scripts.pory"
	.string "My husband was looking for you.$"
# 527 "data/maps/Route34_DayCare/scripts.pory"

# 528 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_FineThenComeAgain:
# 529 "data/maps/Route34_DayCare/scripts.pory"
	.string "Oh, fine, then.\n"
# 530 "data/maps/Route34_DayCare/scripts.pory"
	.string "Come again.$"
# 531 "data/maps/Route34_DayCare/scripts.pory"

# 532 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_NotEnoughMoney:
# 533 "data/maps/Route34_DayCare/scripts.pory"
	.string "You don't have enough money…$"
# 534 "data/maps/Route34_DayCare/scripts.pory"

# 535 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_TakeOtherOneBackToo:
# 536 "data/maps/Route34_DayCare/scripts.pory"
	.string "Will you take back the other one,\n"
# 537 "data/maps/Route34_DayCare/scripts.pory"
	.string "too?$"
# 538 "data/maps/Route34_DayCare/scripts.pory"

# 539 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_ComeAgain:
# 540 "data/maps/Route34_DayCare/scripts.pory"
	.string "Fine.\n"
# 541 "data/maps/Route34_DayCare/scripts.pory"
	.string "Come again.$"
# 542 "data/maps/Route34_DayCare/scripts.pory"

# 543 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_GoodToSeeYou:
# 544 "data/maps/Route34_DayCare/scripts.pory"
	.string "Ah, it's you! Good to see you.\n"
# 545 "data/maps/Route34_DayCare/scripts.pory"
	.string "Your Pokémon can only be doing good!$"
# 546 "data/maps/Route34_DayCare/scripts.pory"

# 547 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_YourMonHasGrownXLevels:
# 548 "data/maps/Route34_DayCare/scripts.pory"
	.string "By level, your {STR_VAR_1} has\n"
# 549 "data/maps/Route34_DayCare/scripts.pory"
	.string "grown by {STR_VAR_2}.$"
# 550 "data/maps/Route34_DayCare/scripts.pory"

# 551 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_YourTeamIsFull:
# 552 "data/maps/Route34_DayCare/scripts.pory"
	.string "Your Pokémon team is full.\n"
# 553 "data/maps/Route34_DayCare/scripts.pory"
	.string "Make room, then come see me.$"
# 554 "data/maps/Route34_DayCare/scripts.pory"

# 555 "data/maps/Route34_DayCare/scripts.pory"
@ Unused
# 556 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_TakeBackWhichMon:
# 557 "data/maps/Route34_DayCare/scripts.pory"
	.string "Which Pokémon will you take back?$"
# 558 "data/maps/Route34_DayCare/scripts.pory"

# 559 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_ItWillCostX:
# 560 "data/maps/Route34_DayCare/scripts.pory"
	.string "If you want your {STR_VAR_1} back,\n"
# 561 "data/maps/Route34_DayCare/scripts.pory"
	.string "it will cost ¥{STR_VAR_2}.$"
# 562 "data/maps/Route34_DayCare/scripts.pory"

# 563 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_HeresYourMon:
# 564 "data/maps/Route34_DayCare/scripts.pory"
	.string "Perfect!\n"
# 565 "data/maps/Route34_DayCare/scripts.pory"
	.string "Here's your Pokémon.$"
# 566 "data/maps/Route34_DayCare/scripts.pory"

# 567 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_TookBackMon:
# 568 "data/maps/Route34_DayCare/scripts.pory"
	.string "{PLAYER} took back {STR_VAR_1} from\n"
# 569 "data/maps/Route34_DayCare/scripts.pory"
	.string "the Day-Care Lady.$"
# 570 "data/maps/Route34_DayCare/scripts.pory"

# 571 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_YouHaveJustOneMon:
# 572 "data/maps/Route34_DayCare/scripts.pory"
	.string "Oh? But you have just one\n"
# 573 "data/maps/Route34_DayCare/scripts.pory"
	.string "Pokémon.\p"
# 574 "data/maps/Route34_DayCare/scripts.pory"
	.string "Come back another time.$"
# 575 "data/maps/Route34_DayCare/scripts.pory"

# 576 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_TakeYourMonBack:
# 577 "data/maps/Route34_DayCare/scripts.pory"
	.string "Will you take your Pokémon back?$"
# 578 "data/maps/Route34_DayCare/scripts.pory"

# 579 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_WhatWillYouBattleWith:
# 580 "data/maps/Route34_DayCare/scripts.pory"
	.string "If you leave me that Pokémon,\n"
# 581 "data/maps/Route34_DayCare/scripts.pory"
	.string "what will you battle with?\p"
# 582 "data/maps/Route34_DayCare/scripts.pory"
	.string "Come back another time.$"
# 583 "data/maps/Route34_DayCare/scripts.pory"

# 584 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_YoullBeLeftWithJustOne:
# 585 "data/maps/Route34_DayCare/scripts.pory"
	.string "Huh?\n"
# 586 "data/maps/Route34_DayCare/scripts.pory"
	.string "Now, now.\p"
# 587 "data/maps/Route34_DayCare/scripts.pory"
	.string "If you leave that Pokémon with\n"
# 588 "data/maps/Route34_DayCare/scripts.pory"
	.string "me, you'll be left with just one.\p"
# 589 "data/maps/Route34_DayCare/scripts.pory"
	.string "You will be better off if you catch\n"
# 590 "data/maps/Route34_DayCare/scripts.pory"
	.string "some more, I dare say.$"

daycareEggGift::
# 594 "data/maps/Route34_DayCare/scripts.pory"
	lock
# 595 "data/maps/Route34_DayCare/scripts.pory"
	faceplayer
# 596 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_set FLAG_RECEIVED_ODD_EGG, daycareEggGift_2
# 602 "data/maps/Route34_DayCare/scripts.pory"
	msgbox daycareEggGift_Text_1, MSGBOX_YESNO
# 609 "data/maps/Route34_DayCare/scripts.pory"
	compare VAR_RESULT, YES
	goto_if_eq daycareEggGift_5
daycareEggGift_4:
# 627 "data/maps/Route34_DayCare/scripts.pory"
	release
	end

daycareEggGift_2:
# 597 "data/maps/Route34_DayCare/scripts.pory"
	msgbox daycareEggGift_Text_0
# 599 "data/maps/Route34_DayCare/scripts.pory"
	release
	end

daycareEggGift_5:
# 610 "data/maps/Route34_DayCare/scripts.pory"
	getpartysize
# 611 "data/maps/Route34_DayCare/scripts.pory"
	compare VAR_RESULT, PARTY_SIZE
	goto_if_eq daycareEggGift_8
# 617 "data/maps/Route34_DayCare/scripts.pory"
	random 7
# 618 "data/maps/Route34_DayCare/scripts.pory"
	addvar VAR_RESULT, 1
# 619 "data/maps/Route34_DayCare/scripts.pory"
	giveoddegg VAR_RESULT
# 620 "data/maps/Route34_DayCare/scripts.pory"
	setflag FLAG_RECEIVED_ODD_EGG
# 621 "data/maps/Route34_DayCare/scripts.pory"
	playfanfare MUS_HG_OBTAIN_ITEM
# 622 "data/maps/Route34_DayCare/scripts.pory"
	message daycareEggGift_Text_3
# 623 "data/maps/Route34_DayCare/scripts.pory"
	waitfanfare
# 624 "data/maps/Route34_DayCare/scripts.pory"
	msgbox daycareEggGift_Text_4
# 625 "data/maps/Route34_DayCare/scripts.pory"
	closemessage
	goto daycareEggGift_4

daycareEggGift_8:
# 612 "data/maps/Route34_DayCare/scripts.pory"
	msgbox daycareEggGift_Text_2
# 613 "data/maps/Route34_DayCare/scripts.pory"
	closemessage
# 614 "data/maps/Route34_DayCare/scripts.pory"
	release
	end


daycareEggGift_Text_0:
# 597 "data/maps/Route34_DayCare/scripts.pory"
	.string "I hope you show lots of love and care\n"
	.string "for the egg.$"

daycareEggGift_Text_1:
# 602 "data/maps/Route34_DayCare/scripts.pory"
	.string "I'm learning from the couple on how to\n"
	.string "raise Pokémon!\l"
	.string "Do you know about eggs? I was raising\l"
	.string "Pokémon as usual and suddenly they\l"
	.string "had laid an egg! We were quite shocked!\l"
	.string "Would you like to take care of it? Don't\l"
	.string "be shy!$"

daycareEggGift_Text_2:
# 612 "data/maps/Route34_DayCare/scripts.pory"
	.string "You have no room for this egg!$"

daycareEggGift_Text_3:
# 622 "data/maps/Route34_DayCare/scripts.pory"
	.string "{PLAYER} Received the Odd Egg.$"

daycareEggGift_Text_4:
# 624 "data/maps/Route34_DayCare/scripts.pory"
	.string "Please take good care of it!$"
