# 1 "data/maps/Route34_DayCare/scripts.pory"

# 2 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_MapScripts::
# 3 "data/maps/Route34_DayCare/scripts.pory"
	.byte 0
# 4 "data/maps/Route34_DayCare/scripts.pory"

# 5 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Bookshelf1::
# 6 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_Bookshelf1, MSGBOX_SIGN
# 7 "data/maps/Route34_DayCare/scripts.pory"
	end
# 8 "data/maps/Route34_DayCare/scripts.pory"

# 9 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Bookshelf2::
# 10 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_Bookshelf2, MSGBOX_SIGN
# 11 "data/maps/Route34_DayCare/scripts.pory"
	end
# 12 "data/maps/Route34_DayCare/scripts.pory"

# 13 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Bookshelf3::
# 14 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_Bookshelf3, MSGBOX_SIGN
# 15 "data/maps/Route34_DayCare/scripts.pory"
	end
# 16 "data/maps/Route34_DayCare/scripts.pory"

# 17 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Bookshelf4::
# 18 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_Bookshelf4, MSGBOX_SIGN
# 19 "data/maps/Route34_DayCare/scripts.pory"
	end
# 20 "data/maps/Route34_DayCare/scripts.pory"

# 21 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_Bookshelf1:
# 22 "data/maps/Route34_DayCare/scripts.pory"
	.string "A dictionary!\p"
# 23 "data/maps/Route34_DayCare/scripts.pory"
	.string "{PLAYER} opened the dictionary to\n"
# 24 "data/maps/Route34_DayCare/scripts.pory"
	.string "a random page.\p"
# 25 "data/maps/Route34_DayCare/scripts.pory"
	.string "'Babe'\n"
# 26 "data/maps/Route34_DayCare/scripts.pory"
	.string "A noun, meaning infant or baby.\p"
# 27 "data/maps/Route34_DayCare/scripts.pory"
	.string "{PLAYER} put away the dictionary.$"
# 28 "data/maps/Route34_DayCare/scripts.pory"

# 29 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_Bookshelf2:
# 30 "data/maps/Route34_DayCare/scripts.pory"
	.string "A book about Pokémon!\p"
# 31 "data/maps/Route34_DayCare/scripts.pory"
	.string "{PLAYER} flipped through\n"
# 32 "data/maps/Route34_DayCare/scripts.pory"
	.string "the book.\p"
# 33 "data/maps/Route34_DayCare/scripts.pory"
	.string "It must have the word\n"
# 34 "data/maps/Route34_DayCare/scripts.pory"
	.string "Pokémon written on every page.\p"
# 35 "data/maps/Route34_DayCare/scripts.pory"
	.string "{PLAYER} put away the book.$"
# 36 "data/maps/Route34_DayCare/scripts.pory"

# 37 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_Bookshelf3:
# 38 "data/maps/Route34_DayCare/scripts.pory"
	.string "A book of word associations!\p"
# 39 "data/maps/Route34_DayCare/scripts.pory"
	.string "{PLAYER} flipped through\n"
# 40 "data/maps/Route34_DayCare/scripts.pory"
	.string "the book.\p"
# 41 "data/maps/Route34_DayCare/scripts.pory"
	.string "Pichu -> Cute\l"
# 42 "data/maps/Route34_DayCare/scripts.pory"
	.string "Cleffa -> Cute\l"
# 43 "data/maps/Route34_DayCare/scripts.pory"
	.string "Igglybuff -> Song\l"
# 44 "data/maps/Route34_DayCare/scripts.pory"
	.string "Tyrogue -> Fighting\l"
# 45 "data/maps/Route34_DayCare/scripts.pory"
	.string "Smoochum -> Ice\l"
# 46 "data/maps/Route34_DayCare/scripts.pory"
	.string "Elekid -> Electric\l"
# 47 "data/maps/Route34_DayCare/scripts.pory"
	.string "Magby -> Fire\p"
# 48 "data/maps/Route34_DayCare/scripts.pory"
	.string "{PLAYER} put away the book.$"
# 49 "data/maps/Route34_DayCare/scripts.pory"

# 50 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_Bookshelf4:
# 51 "data/maps/Route34_DayCare/scripts.pory"
	.string "A book of Pokémon natures!\p"
# 52 "data/maps/Route34_DayCare/scripts.pory"
	.string "{PLAYER} flipped through\n"
# 53 "data/maps/Route34_DayCare/scripts.pory"
	.string "the book.\p"
# 54 "data/maps/Route34_DayCare/scripts.pory"
	.string "Pichu -> Static\l"
# 55 "data/maps/Route34_DayCare/scripts.pory"
	.string "Cleffa -> Cute Charm\l"
# 56 "data/maps/Route34_DayCare/scripts.pory"
	.string "Igglybuff -> Cute Charm\l"
# 57 "data/maps/Route34_DayCare/scripts.pory"
	.string "Tyrogue -> Guts\l"
# 58 "data/maps/Route34_DayCare/scripts.pory"
	.string "Smoochum -> Oblivious\l"
# 59 "data/maps/Route34_DayCare/scripts.pory"
	.string "Elekid -> Static\l"
# 60 "data/maps/Route34_DayCare/scripts.pory"
	.string "Magby -> Flame Body\p"
# 61 "data/maps/Route34_DayCare/scripts.pory"
	.string "{PLAYER} put away the book.$"
# 62 "data/maps/Route34_DayCare/scripts.pory"

# 63 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_Clerk::
# 64 "data/maps/Route34_DayCare/scripts.pory"
	lock
# 65 "data/maps/Route34_DayCare/scripts.pory"
	faceplayer
# 66 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_set FLAG_RECEIVED_ODD_EGG, Route34_DayCare_EventScript_ClerkAfter
# 67 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_ClerkBefore, MSGBOX_DEFAULT
# 68 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_ClerkQuestion, MSGBOX_DEFAULT
# 69 "data/maps/Route34_DayCare/scripts.pory"
	closemessage
# 70 "data/maps/Route34_DayCare/scripts.pory"
	setvar VAR_0x8004, EASY_CHAT_TYPE_INTERVIEW
# 71 "data/maps/Route34_DayCare/scripts.pory"
	setvar VAR_0x8005, 0
# 72 "data/maps/Route34_DayCare/scripts.pory"
	call Common_ShowEasyChatScreen
# 73 "data/maps/Route34_DayCare/scripts.pory"
	lock
# 74 "data/maps/Route34_DayCare/scripts.pory"
	faceplayer
# 75 "data/maps/Route34_DayCare/scripts.pory"
	switch VAR_RESULT
# 76 "data/maps/Route34_DayCare/scripts.pory"
	case 0, Route34_DayCare_EventScript_ClerkRejection
# 77 "data/maps/Route34_DayCare/scripts.pory"
	case 1, Route34_DayCare_EventScript_GivePichu
# 78 "data/maps/Route34_DayCare/scripts.pory"
	case 2, Route34_DayCare_EventScript_GiveCleffa
# 79 "data/maps/Route34_DayCare/scripts.pory"
	case 3, Route34_DayCare_EventScript_GiveIgglybuff
# 80 "data/maps/Route34_DayCare/scripts.pory"
	case 4, Route34_DayCare_EventScript_GiveTyrogue
# 81 "data/maps/Route34_DayCare/scripts.pory"
	case 5, Route34_DayCare_EventScript_GiveSmoochum
# 82 "data/maps/Route34_DayCare/scripts.pory"
	case 6, Route34_DayCare_EventScript_GiveElekid
# 83 "data/maps/Route34_DayCare/scripts.pory"
	case 7, Route34_DayCare_EventScript_GiveMagby
# 84 "data/maps/Route34_DayCare/scripts.pory"
	closemessage
# 85 "data/maps/Route34_DayCare/scripts.pory"
	release
# 86 "data/maps/Route34_DayCare/scripts.pory"
	end
# 87 "data/maps/Route34_DayCare/scripts.pory"

# 88 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_GivePichu::
# 89 "data/maps/Route34_DayCare/scripts.pory"
	giveoddegg 1
# 90 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, MON_CANT_GIVE, Route34_DayCare_EventScript_ClerkPartyFull
# 91 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_Clerk_GaveEgg
# 92 "data/maps/Route34_DayCare/scripts.pory"

# 93 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_GiveCleffa::
# 94 "data/maps/Route34_DayCare/scripts.pory"
	giveoddegg 2
# 95 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, MON_CANT_GIVE, Route34_DayCare_EventScript_ClerkPartyFull
# 96 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_Clerk_GaveEgg
# 97 "data/maps/Route34_DayCare/scripts.pory"

# 98 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_GiveIgglybuff::
# 99 "data/maps/Route34_DayCare/scripts.pory"
	giveoddegg 3
# 100 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, MON_CANT_GIVE, Route34_DayCare_EventScript_ClerkPartyFull
# 101 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_Clerk_GaveEgg
# 102 "data/maps/Route34_DayCare/scripts.pory"

# 103 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_GiveTyrogue::
# 104 "data/maps/Route34_DayCare/scripts.pory"
	giveoddegg 4
# 105 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, MON_CANT_GIVE, Route34_DayCare_EventScript_ClerkPartyFull
# 106 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_Clerk_GaveEgg
# 107 "data/maps/Route34_DayCare/scripts.pory"

# 108 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_GiveSmoochum::
# 109 "data/maps/Route34_DayCare/scripts.pory"
	giveoddegg 5
# 110 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, MON_CANT_GIVE, Route34_DayCare_EventScript_ClerkPartyFull
# 111 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_Clerk_GaveEgg
# 112 "data/maps/Route34_DayCare/scripts.pory"

# 113 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_GiveElekid::
# 114 "data/maps/Route34_DayCare/scripts.pory"
	giveoddegg 6
# 115 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, MON_CANT_GIVE, Route34_DayCare_EventScript_ClerkPartyFull
# 116 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_Clerk_GaveEgg
# 117 "data/maps/Route34_DayCare/scripts.pory"

# 118 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_GiveMagby::
# 119 "data/maps/Route34_DayCare/scripts.pory"
	giveoddegg 7
# 120 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, MON_CANT_GIVE, Route34_DayCare_EventScript_ClerkPartyFull
# 121 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_Clerk_GaveEgg
# 122 "data/maps/Route34_DayCare/scripts.pory"

# 123 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_Clerk_GaveEgg::
# 124 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_TakeCare, MSGBOX_DEFAULT
# 125 "data/maps/Route34_DayCare/scripts.pory"
	closemessage
# 126 "data/maps/Route34_DayCare/scripts.pory"
	delay 30
# 127 "data/maps/Route34_DayCare/scripts.pory"
	setflag FLAG_RECEIVED_ODD_EGG
# 128 "data/maps/Route34_DayCare/scripts.pory"
	playfanfare MUS_OBTAIN_ITEM
# 129 "data/maps/Route34_DayCare/scripts.pory"
	message Route34_DayCare_Text_ReceivedOddEgg
# 130 "data/maps/Route34_DayCare/scripts.pory"
	waitfanfare
# 131 "data/maps/Route34_DayCare/scripts.pory"
	closemessage
# 132 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, MON_GIVEN_TO_PC, Route34_DayCare_EventScript_Clerk_GaveEggToPC
# 133 "data/maps/Route34_DayCare/scripts.pory"
	release
# 134 "data/maps/Route34_DayCare/scripts.pory"
	end
# 135 "data/maps/Route34_DayCare/scripts.pory"

# 136 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_Clerk_GaveEggToPC::
# 137 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_OddEggSentToPC, MSGBOX_DEFAULT
# 138 "data/maps/Route34_DayCare/scripts.pory"
	closemessage
# 139 "data/maps/Route34_DayCare/scripts.pory"
	release
# 140 "data/maps/Route34_DayCare/scripts.pory"
	end
# 141 "data/maps/Route34_DayCare/scripts.pory"

# 142 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_ClerkPartyFull::
# 143 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_ClerkNoRoom, MSGBOX_DEFAULT
# 144 "data/maps/Route34_DayCare/scripts.pory"
	closemessage
# 145 "data/maps/Route34_DayCare/scripts.pory"
	release
# 146 "data/maps/Route34_DayCare/scripts.pory"
	end
# 147 "data/maps/Route34_DayCare/scripts.pory"

# 148 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_ClerkRejection::
# 149 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_Rejection, MSGBOX_DEFAULT
# 150 "data/maps/Route34_DayCare/scripts.pory"
	closemessage
# 151 "data/maps/Route34_DayCare/scripts.pory"
	release
# 152 "data/maps/Route34_DayCare/scripts.pory"
	end
# 153 "data/maps/Route34_DayCare/scripts.pory"

# 154 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_ClerkAfter::
# 155 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_ClerkAfter, MSGBOX_DEFAULT
# 156 "data/maps/Route34_DayCare/scripts.pory"
	closemessage
# 157 "data/maps/Route34_DayCare/scripts.pory"
	release
# 158 "data/maps/Route34_DayCare/scripts.pory"
	end
# 159 "data/maps/Route34_DayCare/scripts.pory"

# 160 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_ClerkBefore:
# 161 "data/maps/Route34_DayCare/scripts.pory"
	.string "I'm the Daycare couple's son.\p"
# 162 "data/maps/Route34_DayCare/scripts.pory"
	.string "An Odd Egg was found with a trainer's\n"
# 163 "data/maps/Route34_DayCare/scripts.pory"
	.string "Pokémon, but they didn't want it...\p"
# 164 "data/maps/Route34_DayCare/scripts.pory"
	.string "I'd offer it to you...\n"
# 165 "data/maps/Route34_DayCare/scripts.pory"
	.string "But how can I know you'll take good\l"
# 166 "data/maps/Route34_DayCare/scripts.pory"
	.string "care of it?$"
# 167 "data/maps/Route34_DayCare/scripts.pory"

# 168 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_ClerkNoRoom:
# 169 "data/maps/Route34_DayCare/scripts.pory"
	.string "It looks like you can't carry another\n"
# 170 "data/maps/Route34_DayCare/scripts.pory"
	.string "Pokémon anyway.$"
# 171 "data/maps/Route34_DayCare/scripts.pory"

# 172 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_ClerkQuestion:
# 173 "data/maps/Route34_DayCare/scripts.pory"
	.string "Answer this question for me.\n"
# 174 "data/maps/Route34_DayCare/scripts.pory"
	.string "How do you feel about this Odd Egg?$"
# 175 "data/maps/Route34_DayCare/scripts.pory"

# 176 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_Rejection:
# 177 "data/maps/Route34_DayCare/scripts.pory"
	.string "Hmm, I think this egg isn't for you.\p"
# 178 "data/maps/Route34_DayCare/scripts.pory"
	.string "It would be irresponsible of me to\n"
# 179 "data/maps/Route34_DayCare/scripts.pory"
	.string "give out a precious Egg like this\l"
# 180 "data/maps/Route34_DayCare/scripts.pory"
	.string "to someone who isn't as well-read\l"
# 181 "data/maps/Route34_DayCare/scripts.pory"
	.string "on the subject of Pokémon breeding!$"
# 182 "data/maps/Route34_DayCare/scripts.pory"

# 183 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_ReceivedOddEgg:
# 184 "data/maps/Route34_DayCare/scripts.pory"
	.string "{PLAYER} Received the Odd Egg.$"
# 185 "data/maps/Route34_DayCare/scripts.pory"

# 186 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_OddEggSentToPC:
# 187 "data/maps/Route34_DayCare/scripts.pory"
	.string "The Odd Egg was sent to your PC.$"
# 188 "data/maps/Route34_DayCare/scripts.pory"

# 189 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_TakeCare:
# 190 "data/maps/Route34_DayCare/scripts.pory"
	.string "I knew you were the right trainer\n"
# 191 "data/maps/Route34_DayCare/scripts.pory"
	.string "for the job. Take good care of it!$"
# 192 "data/maps/Route34_DayCare/scripts.pory"

# 193 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_ClerkAfter:
# 194 "data/maps/Route34_DayCare/scripts.pory"
	.string "We see a lot of those eggs around\n"
# 195 "data/maps/Route34_DayCare/scripts.pory"
	.string "here.\p"
# 196 "data/maps/Route34_DayCare/scripts.pory"
	.string "Something was different about that\n"
# 197 "data/maps/Route34_DayCare/scripts.pory"
	.string "one, though.$"
# 198 "data/maps/Route34_DayCare/scripts.pory"

# 199 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_Ditto::
# 200 "data/maps/Route34_DayCare/scripts.pory"
	lock
# 201 "data/maps/Route34_DayCare/scripts.pory"
	faceplayer
# 202 "data/maps/Route34_DayCare/scripts.pory"
	waitse
# 203 "data/maps/Route34_DayCare/scripts.pory"
	playmoncry SPECIES_DITTO, CRY_MODE_NORMAL
# 204 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_Ditto, MSGBOX_DEFAULT
# 205 "data/maps/Route34_DayCare/scripts.pory"
	waitmoncry
# 206 "data/maps/Route34_DayCare/scripts.pory"
	release
# 207 "data/maps/Route34_DayCare/scripts.pory"
	end
# 208 "data/maps/Route34_DayCare/scripts.pory"

# 209 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_Ditto:
# 210 "data/maps/Route34_DayCare/scripts.pory"
	.string "Ditto: Tto!$"
# 211 "data/maps/Route34_DayCare/scripts.pory"

# 212 "data/maps/Route34_DayCare/scripts.pory"
Route34_EventScript_DaycareMan::
# 213 "data/maps/Route34_DayCare/scripts.pory"
	lock
# 214 "data/maps/Route34_DayCare/scripts.pory"
	faceplayer
# 215 "data/maps/Route34_DayCare/scripts.pory"
	special GetDaycareMonNicknames
# 216 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, GetDaycareState
# 217 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, DAYCARE_EGG_WAITING, Route34_EventScript_DaycareEggWaiting
# 218 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, DAYCARE_ONE_MON, Route34_EventScript_CheckOnOneMon
# 219 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, DAYCARE_TWO_MONS, Route34_EventScript_CheckOnTwoMons
# 220 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_Text_SeeWifeIfYoudLikeMeToRaiseMon, MSGBOX_DEFAULT
# 221 "data/maps/Route34_DayCare/scripts.pory"
	release
# 222 "data/maps/Route34_DayCare/scripts.pory"
	end
# 223 "data/maps/Route34_DayCare/scripts.pory"

# 224 "data/maps/Route34_DayCare/scripts.pory"
Route34_EventScript_DaycareEggWaiting::
# 225 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_Text_DoYouWantEgg, MSGBOX_YESNO
# 226 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, YES, Route34_EventScript_DaycareAcceptEgg
# 227 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_Text_IWillKeepDoYouWantIt, MSGBOX_YESNO
# 228 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, YES, Route34_EventScript_DaycareAcceptEgg
# 229 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_Text_IllKeepIt, MSGBOX_DEFAULT
# 230 "data/maps/Route34_DayCare/scripts.pory"
	clearflag FLAG_PENDING_DAYCARE_EGG
# 231 "data/maps/Route34_DayCare/scripts.pory"
	special RejectEggFromDayCare
# 232 "data/maps/Route34_DayCare/scripts.pory"
	release
# 233 "data/maps/Route34_DayCare/scripts.pory"
	end
# 234 "data/maps/Route34_DayCare/scripts.pory"

# 235 "data/maps/Route34_DayCare/scripts.pory"
Route34_EventScript_DaycareAcceptEgg::
# 236 "data/maps/Route34_DayCare/scripts.pory"
	@specialvar VAR_0x8004, GetMaxPartySize @ tx_randomizer_and_challenges
# 237 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, CalculatePlayerPartyCount
# 238 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_ne VAR_RESULT, VAR_0x8004, Route34_EventScript_DaycareReceiveEgg
# 239 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_Text_YouHaveNoRoomForIt, MSGBOX_DEFAULT
# 240 "data/maps/Route34_DayCare/scripts.pory"
	release
# 241 "data/maps/Route34_DayCare/scripts.pory"
	end
# 242 "data/maps/Route34_DayCare/scripts.pory"

# 243 "data/maps/Route34_DayCare/scripts.pory"
Route34_EventScript_DaycareReceiveEgg::
# 244 "data/maps/Route34_DayCare/scripts.pory"
	message Route34_Text_ReceivedEgg
# 245 "data/maps/Route34_DayCare/scripts.pory"
	playfanfare MUS_LEVEL_UP
# 246 "data/maps/Route34_DayCare/scripts.pory"
	waitfanfare
# 247 "data/maps/Route34_DayCare/scripts.pory"
	waitbuttonpress
# 248 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_Text_TakeGoodCareOfIt, MSGBOX_DEFAULT
# 249 "data/maps/Route34_DayCare/scripts.pory"
	special GiveEggFromDaycare
# 250 "data/maps/Route34_DayCare/scripts.pory"
	clearflag FLAG_PENDING_DAYCARE_EGG
# 251 "data/maps/Route34_DayCare/scripts.pory"
	release
# 252 "data/maps/Route34_DayCare/scripts.pory"
	end
# 253 "data/maps/Route34_DayCare/scripts.pory"

# 254 "data/maps/Route34_DayCare/scripts.pory"
Route34_EventScript_CheckMonReceivedMail::
# 255 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, CheckDaycareMonReceivedMail
# 256 "data/maps/Route34_DayCare/scripts.pory"
	call_if_eq VAR_RESULT, 1, Route34_EventScript_MonReceivedMail
# 257 "data/maps/Route34_DayCare/scripts.pory"
	return
# 258 "data/maps/Route34_DayCare/scripts.pory"

# 259 "data/maps/Route34_DayCare/scripts.pory"
Route34_EventScript_MonReceivedMail::
# 260 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_Text_FriendlyWithOtherTrainersMon, MSGBOX_DEFAULT
# 261 "data/maps/Route34_DayCare/scripts.pory"
	return
# 262 "data/maps/Route34_DayCare/scripts.pory"

# 263 "data/maps/Route34_DayCare/scripts.pory"
Route34_EventScript_CheckOnOneMon::
# 264 "data/maps/Route34_DayCare/scripts.pory"
	special GetDaycareMonNicknames
# 265 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_Text_YourMonIsDoingFine, MSGBOX_DEFAULT
# 266 "data/maps/Route34_DayCare/scripts.pory"
	setvar VAR_0x8004, 0
# 267 "data/maps/Route34_DayCare/scripts.pory"
	call Route34_EventScript_CheckMonReceivedMail
# 268 "data/maps/Route34_DayCare/scripts.pory"
	release
# 269 "data/maps/Route34_DayCare/scripts.pory"
	end
# 270 "data/maps/Route34_DayCare/scripts.pory"

# 271 "data/maps/Route34_DayCare/scripts.pory"
Route34_EventScript_CheckOnTwoMons::
# 272 "data/maps/Route34_DayCare/scripts.pory"
	special GetDaycareMonNicknames
# 273 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_Text_YourMonsAreDoingFine, MSGBOX_DEFAULT
# 274 "data/maps/Route34_DayCare/scripts.pory"
	special SetDaycareCompatibilityString
# 275 "data/maps/Route34_DayCare/scripts.pory"
	special ShowFieldMessageStringVar4
# 276 "data/maps/Route34_DayCare/scripts.pory"
	waitmessage
# 277 "data/maps/Route34_DayCare/scripts.pory"
	waitbuttonpress
# 278 "data/maps/Route34_DayCare/scripts.pory"
	setvar VAR_0x8004, 0
# 279 "data/maps/Route34_DayCare/scripts.pory"
	call Route34_EventScript_CheckMonReceivedMail
# 280 "data/maps/Route34_DayCare/scripts.pory"
	setvar VAR_0x8004, 1
# 281 "data/maps/Route34_DayCare/scripts.pory"
	call Route34_EventScript_CheckMonReceivedMail
# 282 "data/maps/Route34_DayCare/scripts.pory"
	release
# 283 "data/maps/Route34_DayCare/scripts.pory"
	end
# 284 "data/maps/Route34_DayCare/scripts.pory"

# 285 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_DaycareWoman::
# 286 "data/maps/Route34_DayCare/scripts.pory"
	lock
# 287 "data/maps/Route34_DayCare/scripts.pory"
	faceplayer
# 288 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, GetDaycareState
# 289 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, DAYCARE_EGG_WAITING, Route34_DayCare_EventScript_EggWaiting
# 290 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, DAYCARE_ONE_MON, Route34_DayCare_EventScript_OneMonInDaycare
# 291 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, DAYCARE_TWO_MONS, Route34_DayCare_EventScript_TwoMonsInDaycare
# 292 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_WouldYouLikeUsToRaiseAMon, MSGBOX_YESNO
# 293 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, YES, Route34_DayCare_EventScript_GiveMonToRaise
# 294 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_FineThenComeAgain, MSGBOX_DEFAULT
# 295 "data/maps/Route34_DayCare/scripts.pory"
	release
# 296 "data/maps/Route34_DayCare/scripts.pory"
	end
# 297 "data/maps/Route34_DayCare/scripts.pory"

# 298 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_GiveMonToRaise::
# 299 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, CountPartyNonEggMons
# 300 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, 1, Route34_DayCare_EventScript_OnlyOneMon
# 301 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, CountPartyAliveNonEggMons
# 302 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, 2, Route34_DayCare_EventScript_OnlyTwoAliveMons
# 303 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_WhichMonShouldWeRaise, MSGBOX_DEFAULT
# 304 "data/maps/Route34_DayCare/scripts.pory"
	fadescreen FADE_TO_BLACK
# 305 "data/maps/Route34_DayCare/scripts.pory"
	special ChooseSendDaycareMon
# 306 "data/maps/Route34_DayCare/scripts.pory"
	waitstate
# 307 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_0x8004, PARTY_NOTHING_CHOSEN, Route34_DayCare_EventScript_ComeAgain
# 308 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, CountPartyAliveNonEggMons_IgnoreVar0x8004Slot
# 309 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, 0, Route34_DayCare_EventScript_OnlyOneAliveMon
# 310 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_0x8005, GetSelectedMonNicknameAndSpecies
# 311 "data/maps/Route34_DayCare/scripts.pory"
	waitse
# 312 "data/maps/Route34_DayCare/scripts.pory"
	playmoncry VAR_0x8005, CRY_MODE_NORMAL
# 313 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_WellRaiseYourMon, MSGBOX_DEFAULT
# 314 "data/maps/Route34_DayCare/scripts.pory"
	waitmoncry
# 315 "data/maps/Route34_DayCare/scripts.pory"
	special StoreSelectedPokemonInDaycare
# 316 "data/maps/Route34_DayCare/scripts.pory"
	callnative UpdateFollowingPokemon
# 317 "data/maps/Route34_DayCare/scripts.pory"
	incrementgamestat GAME_STAT_USED_DAYCARE
# 318 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, GetDaycareState
# 319 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, DAYCARE_ONE_MON, Route34_DayCare_EventScript_CanRaiseOneMore
# 320 "data/maps/Route34_DayCare/scripts.pory"
	release
# 321 "data/maps/Route34_DayCare/scripts.pory"
	end
# 322 "data/maps/Route34_DayCare/scripts.pory"

# 323 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_ComeAgain::
# 324 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_ComeAgain, MSGBOX_DEFAULT
# 325 "data/maps/Route34_DayCare/scripts.pory"
	release
# 326 "data/maps/Route34_DayCare/scripts.pory"
	end
# 327 "data/maps/Route34_DayCare/scripts.pory"

# 328 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_CanRaiseOneMore::
# 329 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_WeCanRaiseOneMore, MSGBOX_YESNO
# 330 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, YES, Route34_DayCare_EventScript_GiveMonToRaise
# 331 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_ComeAgain
# 332 "data/maps/Route34_DayCare/scripts.pory"
	end
# 333 "data/maps/Route34_DayCare/scripts.pory"

# 334 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_OnlyOneMon::
# 335 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_YouHaveJustOneMon, MSGBOX_DEFAULT
# 336 "data/maps/Route34_DayCare/scripts.pory"
	release
# 337 "data/maps/Route34_DayCare/scripts.pory"
	end
# 338 "data/maps/Route34_DayCare/scripts.pory"

# 339 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_OnlyOneAliveMon::
# 340 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_WhatWillYouBattleWith, MSGBOX_DEFAULT
# 341 "data/maps/Route34_DayCare/scripts.pory"
	release
# 342 "data/maps/Route34_DayCare/scripts.pory"
	end
# 343 "data/maps/Route34_DayCare/scripts.pory"

# 344 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_OnlyTwoAliveMons::
# 345 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_YoullBeLeftWithJustOne, MSGBOX_DEFAULT
# 346 "data/maps/Route34_DayCare/scripts.pory"
	release
# 347 "data/maps/Route34_DayCare/scripts.pory"
	end
# 348 "data/maps/Route34_DayCare/scripts.pory"

# 349 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_EggWaiting::
# 350 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_HusbandWasLookingForYou, MSGBOX_DEFAULT
# 351 "data/maps/Route34_DayCare/scripts.pory"
	release
# 352 "data/maps/Route34_DayCare/scripts.pory"
	end
# 353 "data/maps/Route34_DayCare/scripts.pory"

# 354 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_YourMonHasGrownXLevels::
# 355 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_YourMonHasGrownXLevels, MSGBOX_DEFAULT
# 356 "data/maps/Route34_DayCare/scripts.pory"
	return
# 357 "data/maps/Route34_DayCare/scripts.pory"

# 358 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_DisplayLevelsGained::
# 359 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, GetNumLevelsGainedFromDaycare
# 360 "data/maps/Route34_DayCare/scripts.pory"
	call_if_ne VAR_RESULT, 0, Route34_DayCare_EventScript_YourMonHasGrownXLevels
# 361 "data/maps/Route34_DayCare/scripts.pory"
	return
# 362 "data/maps/Route34_DayCare/scripts.pory"

# 363 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_OneMonInDaycare::
# 364 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_GoodToSeeYou, MSGBOX_DEFAULT
# 365 "data/maps/Route34_DayCare/scripts.pory"
	setvar VAR_0x8004, 0
# 366 "data/maps/Route34_DayCare/scripts.pory"
	call Route34_DayCare_EventScript_DisplayLevelsGained
# 367 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_WeCanRaiseOneMore, MSGBOX_YESNO
# 368 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, YES, Route34_DayCare_EventScript_GiveMonToRaise
# 369 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_TakeYourMonBack, MSGBOX_YESNO
# 370 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, YES, Route34_DayCare_EventScript_TryRetrieveMon
# 371 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_ComeAgain
# 372 "data/maps/Route34_DayCare/scripts.pory"
	end
# 373 "data/maps/Route34_DayCare/scripts.pory"

# 374 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_TryRetrieveMon::
# 375 "data/maps/Route34_DayCare/scripts.pory"
	@specialvar VAR_0x8004, GetMaxPartySize @ tx_randomizer_and_challenges
# 376 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, CalculatePlayerPartyCount
# 377 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, VAR_0x8004, Route34_DayCare_EventScript_NoRoom
# 378 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, GetDaycareState
# 379 "data/maps/Route34_DayCare/scripts.pory"
	setvar VAR_0x8004, 0
# 380 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, DAYCARE_ONE_MON, Route34_DayCare_EventScript_CostPrompt
# 381 "data/maps/Route34_DayCare/scripts.pory"
	special ShowDaycareLevelMenu
# 382 "data/maps/Route34_DayCare/scripts.pory"
	waitstate
# 383 "data/maps/Route34_DayCare/scripts.pory"
	copyvar VAR_0x8004, VAR_RESULT
# 384 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, DAYCARE_EXITED_LEVEL_MENU, Route34_DayCare_EventScript_ComeAgain
# 385 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_CostPrompt
# 386 "data/maps/Route34_DayCare/scripts.pory"
	end
# 387 "data/maps/Route34_DayCare/scripts.pory"

# 388 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_CostPrompt::
# 389 "data/maps/Route34_DayCare/scripts.pory"
	special GetDaycareCost
# 390 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_ItWillCostX, MSGBOX_YESNO
# 391 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, YES, Route34_DayCare_EventScript_CheckEnoughMoney
# 392 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_ComeAgain
# 393 "data/maps/Route34_DayCare/scripts.pory"
	end
# 394 "data/maps/Route34_DayCare/scripts.pory"

# 395 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_CheckEnoughMoney::
# 396 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, IsEnoughForCostInVar0x8005
# 397 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, 1, Route34_DayCare_EventScript_RetrieveMon
# 398 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_NotEnoughMoney, MSGBOX_DEFAULT
# 399 "data/maps/Route34_DayCare/scripts.pory"
	release
# 400 "data/maps/Route34_DayCare/scripts.pory"
	end
# 401 "data/maps/Route34_DayCare/scripts.pory"

# 402 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_RetrieveMon::
# 403 "data/maps/Route34_DayCare/scripts.pory"
	@applymovement LOCALID_DAYCARE_LADY, Route34_DayCare_Movement_RetrieveDaycareMon
# 404 "data/maps/Route34_DayCare/scripts.pory"
	@waitmovement 0
# 405 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, TakePokemonFromDaycare
# 406 "data/maps/Route34_DayCare/scripts.pory"
	special SubtractMoneyFromVar0x8005
# 407 "data/maps/Route34_DayCare/scripts.pory"
	playse SE_SHOP
# 408 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_HeresYourMon, MSGBOX_DEFAULT
# 409 "data/maps/Route34_DayCare/scripts.pory"
	waitse
# 410 "data/maps/Route34_DayCare/scripts.pory"
	playmoncry VAR_RESULT, CRY_MODE_NORMAL
# 411 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_TookBackMon, MSGBOX_DEFAULT
# 412 "data/maps/Route34_DayCare/scripts.pory"
	waitmoncry
# 413 "data/maps/Route34_DayCare/scripts.pory"
	specialvar VAR_RESULT, GetDaycareState
# 414 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, DAYCARE_ONE_MON, Route34_DayCare_EventScript_AskRetrieveOtherMon
# 415 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_ComeAgain
# 416 "data/maps/Route34_DayCare/scripts.pory"
	end
# 417 "data/maps/Route34_DayCare/scripts.pory"

# 418 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_AskRetrieveOtherMon::
# 419 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_TakeOtherOneBackToo, MSGBOX_YESNO
# 420 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, YES, Route34_DayCare_EventScript_TryRetrieveMon
# 421 "data/maps/Route34_DayCare/scripts.pory"
	goto Route34_DayCare_EventScript_ComeAgain
# 422 "data/maps/Route34_DayCare/scripts.pory"
	end
# 423 "data/maps/Route34_DayCare/scripts.pory"

# 424 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_NoRoom::
# 425 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_YourTeamIsFull, MSGBOX_DEFAULT
# 426 "data/maps/Route34_DayCare/scripts.pory"
	release
# 427 "data/maps/Route34_DayCare/scripts.pory"
	end
# 428 "data/maps/Route34_DayCare/scripts.pory"

# 429 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Movement_RetrieveDaycareMon:
# 430 "data/maps/Route34_DayCare/scripts.pory"
	delay_16
# 431 "data/maps/Route34_DayCare/scripts.pory"
	delay_16
# 432 "data/maps/Route34_DayCare/scripts.pory"
	face_left
# 433 "data/maps/Route34_DayCare/scripts.pory"
	delay_16
# 434 "data/maps/Route34_DayCare/scripts.pory"
	delay_16
# 435 "data/maps/Route34_DayCare/scripts.pory"
	face_right
# 436 "data/maps/Route34_DayCare/scripts.pory"
	delay_16
# 437 "data/maps/Route34_DayCare/scripts.pory"
	delay_16
# 438 "data/maps/Route34_DayCare/scripts.pory"
	face_up
# 439 "data/maps/Route34_DayCare/scripts.pory"
	walk_slow_up
# 440 "data/maps/Route34_DayCare/scripts.pory"
	set_invisible
# 441 "data/maps/Route34_DayCare/scripts.pory"
	delay_16
# 442 "data/maps/Route34_DayCare/scripts.pory"
	delay_16
# 443 "data/maps/Route34_DayCare/scripts.pory"
	delay_16
# 444 "data/maps/Route34_DayCare/scripts.pory"
	delay_16
# 445 "data/maps/Route34_DayCare/scripts.pory"
	delay_16
# 446 "data/maps/Route34_DayCare/scripts.pory"
	face_down
# 447 "data/maps/Route34_DayCare/scripts.pory"
	set_visible
# 448 "data/maps/Route34_DayCare/scripts.pory"
	walk_slow_down
# 449 "data/maps/Route34_DayCare/scripts.pory"
	step_end
# 450 "data/maps/Route34_DayCare/scripts.pory"

# 451 "data/maps/Route34_DayCare/scripts.pory"
@ Unused. Possibly a commented script, or a typo end added to the above Movement script
# 452 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_UnusedEnd::
# 453 "data/maps/Route34_DayCare/scripts.pory"
	end
# 454 "data/maps/Route34_DayCare/scripts.pory"

# 455 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_EventScript_TwoMonsInDaycare::
# 456 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_GoodToSeeYou, MSGBOX_DEFAULT
# 457 "data/maps/Route34_DayCare/scripts.pory"
	setvar VAR_0x8004, 0
# 458 "data/maps/Route34_DayCare/scripts.pory"
	call Route34_DayCare_EventScript_DisplayLevelsGained
# 459 "data/maps/Route34_DayCare/scripts.pory"
	setvar VAR_0x8004, 1
# 460 "data/maps/Route34_DayCare/scripts.pory"
	call Route34_DayCare_EventScript_DisplayLevelsGained
# 461 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_TakeYourMonBack, MSGBOX_YESNO
# 462 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_eq VAR_RESULT, YES, Route34_DayCare_EventScript_TryRetrieveMon
# 463 "data/maps/Route34_DayCare/scripts.pory"
	msgbox Route34_DayCare_Text_ComeAgain, MSGBOX_DEFAULT
# 464 "data/maps/Route34_DayCare/scripts.pory"
	release
# 465 "data/maps/Route34_DayCare/scripts.pory"
	end
# 466 "data/maps/Route34_DayCare/scripts.pory"

# 467 "data/maps/Route34_DayCare/scripts.pory"
Route34_Text_SeeWifeIfYoudLikeMeToRaiseMon:
# 468 "data/maps/Route34_DayCare/scripts.pory"
	.string "I'm the Day-Care Man.\p"
# 469 "data/maps/Route34_DayCare/scripts.pory"
	.string "I help take care of the precious\n"
# 470 "data/maps/Route34_DayCare/scripts.pory"
	.string "Pokémon of Trainers.\p"
# 471 "data/maps/Route34_DayCare/scripts.pory"
	.string "If you'd like me to raise your Pokémon,\n"
# 472 "data/maps/Route34_DayCare/scripts.pory"
	.string "have a word with my wife.$"
# 473 "data/maps/Route34_DayCare/scripts.pory"

# 474 "data/maps/Route34_DayCare/scripts.pory"
Route34_Text_DoYouWantEgg:
# 475 "data/maps/Route34_DayCare/scripts.pory"
	.string "Ah, it's you!\p"
# 476 "data/maps/Route34_DayCare/scripts.pory"
	.string "We were raising your Pokémon,\n"
# 477 "data/maps/Route34_DayCare/scripts.pory"
	.string "and my goodness, were we surprised!\p"
# 478 "data/maps/Route34_DayCare/scripts.pory"
	.string "Your Pokémon had an Egg!\p"
# 479 "data/maps/Route34_DayCare/scripts.pory"
	.string "We don't know how it got there,\n"
# 480 "data/maps/Route34_DayCare/scripts.pory"
	.string "but your Pokémon had it.\p"
# 481 "data/maps/Route34_DayCare/scripts.pory"
	.string "You do want it, yes?$"
# 482 "data/maps/Route34_DayCare/scripts.pory"

# 483 "data/maps/Route34_DayCare/scripts.pory"
Route34_Text_YourMonIsDoingFine:
# 484 "data/maps/Route34_DayCare/scripts.pory"
	.string "Ah, it's you! Good to see you.\n"
# 485 "data/maps/Route34_DayCare/scripts.pory"
	.string "Your {STR_VAR_1}'s doing fine.$"
# 486 "data/maps/Route34_DayCare/scripts.pory"

# 487 "data/maps/Route34_DayCare/scripts.pory"
Route34_Text_IllKeepIt:
# 488 "data/maps/Route34_DayCare/scripts.pory"
	.string "Well then, I'll keep it.\n"
# 489 "data/maps/Route34_DayCare/scripts.pory"
	.string "Thanks!$"
# 490 "data/maps/Route34_DayCare/scripts.pory"

# 491 "data/maps/Route34_DayCare/scripts.pory"
Route34_Text_YouHaveNoRoomForIt:
# 492 "data/maps/Route34_DayCare/scripts.pory"
	.string "You have no room for it…\n"
# 493 "data/maps/Route34_DayCare/scripts.pory"
	.string "Come back when you've made room.$"
# 494 "data/maps/Route34_DayCare/scripts.pory"

# 495 "data/maps/Route34_DayCare/scripts.pory"
Route34_Text_ReceivedEgg:
# 496 "data/maps/Route34_DayCare/scripts.pory"
	.string "{PLAYER} received the Egg from\n"
# 497 "data/maps/Route34_DayCare/scripts.pory"
	.string "the Day-Care Man.$"
# 498 "data/maps/Route34_DayCare/scripts.pory"

# 499 "data/maps/Route34_DayCare/scripts.pory"
Route34_Text_TakeGoodCareOfIt:
# 500 "data/maps/Route34_DayCare/scripts.pory"
	.string "Take good care of it.$"
# 501 "data/maps/Route34_DayCare/scripts.pory"

# 502 "data/maps/Route34_DayCare/scripts.pory"
Route34_Text_FriendlyWithOtherTrainersMon:
# 503 "data/maps/Route34_DayCare/scripts.pory"
	.string "By the way, about your {STR_VAR_1},\n"
# 504 "data/maps/Route34_DayCare/scripts.pory"
	.string "it seemed to be friendly with\l"
# 505 "data/maps/Route34_DayCare/scripts.pory"
	.string "{STR_VAR_2}'s {STR_VAR_3}.\p"
# 506 "data/maps/Route34_DayCare/scripts.pory"
	.string "I may even have seen it receiving\n"
# 507 "data/maps/Route34_DayCare/scripts.pory"
	.string "a piece of Mail.$"
# 508 "data/maps/Route34_DayCare/scripts.pory"

# 509 "data/maps/Route34_DayCare/scripts.pory"
@ Unused
# 510 "data/maps/Route34_DayCare/scripts.pory"
Route34_Text_SeeWifeIfYouWantToPickUpMon:
# 511 "data/maps/Route34_DayCare/scripts.pory"
	.string "If you want to pick up your Pokémon,\n"
# 512 "data/maps/Route34_DayCare/scripts.pory"
	.string "have a word with my wife.$"
# 513 "data/maps/Route34_DayCare/scripts.pory"

# 514 "data/maps/Route34_DayCare/scripts.pory"
Route34_Text_YourMonsAreDoingFine:
# 515 "data/maps/Route34_DayCare/scripts.pory"
	.string "Ah, it's you! Your {STR_VAR_1} and\n"
# 516 "data/maps/Route34_DayCare/scripts.pory"
	.string "{STR_VAR_2} are doing fine.$"
# 517 "data/maps/Route34_DayCare/scripts.pory"

# 518 "data/maps/Route34_DayCare/scripts.pory"
Route34_Text_IWillKeepDoYouWantIt:
# 519 "data/maps/Route34_DayCare/scripts.pory"
	.string "I really will keep it.\n"
# 520 "data/maps/Route34_DayCare/scripts.pory"
	.string "You do want this, yes?$"
# 521 "data/maps/Route34_DayCare/scripts.pory"

# 522 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_WouldYouLikeUsToRaiseAMon:
# 523 "data/maps/Route34_DayCare/scripts.pory"
	.string "I'm the Day-Care Lady.\p"
# 524 "data/maps/Route34_DayCare/scripts.pory"
	.string "We can raise Pokémon for you.\p"
# 525 "data/maps/Route34_DayCare/scripts.pory"
	.string "Would you like us to raise one?$"
# 526 "data/maps/Route34_DayCare/scripts.pory"

# 527 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_WhichMonShouldWeRaise:
# 528 "data/maps/Route34_DayCare/scripts.pory"
	.string "Which Pokémon should we raise for\n"
# 529 "data/maps/Route34_DayCare/scripts.pory"
	.string "you?$"
# 530 "data/maps/Route34_DayCare/scripts.pory"

# 531 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_WellRaiseYourMon:
# 532 "data/maps/Route34_DayCare/scripts.pory"
	.string "Fine, we'll raise your {STR_VAR_1}\n"
# 533 "data/maps/Route34_DayCare/scripts.pory"
	.string "for a while.\p"
# 534 "data/maps/Route34_DayCare/scripts.pory"
	.string "Come back for it later.$"
# 535 "data/maps/Route34_DayCare/scripts.pory"

# 536 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_WeCanRaiseOneMore:
# 537 "data/maps/Route34_DayCare/scripts.pory"
	.string "We can raise two of your Pokémon.\n"
# 538 "data/maps/Route34_DayCare/scripts.pory"
	.string "Would you like us to raise one more?$"
# 539 "data/maps/Route34_DayCare/scripts.pory"

# 540 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_HusbandWasLookingForYou:
# 541 "data/maps/Route34_DayCare/scripts.pory"
	.string "My husband was looking for you.$"
# 542 "data/maps/Route34_DayCare/scripts.pory"

# 543 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_FineThenComeAgain:
# 544 "data/maps/Route34_DayCare/scripts.pory"
	.string "Oh, fine, then.\n"
# 545 "data/maps/Route34_DayCare/scripts.pory"
	.string "Come again.$"
# 546 "data/maps/Route34_DayCare/scripts.pory"

# 547 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_NotEnoughMoney:
# 548 "data/maps/Route34_DayCare/scripts.pory"
	.string "You don't have enough money…$"
# 549 "data/maps/Route34_DayCare/scripts.pory"

# 550 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_TakeOtherOneBackToo:
# 551 "data/maps/Route34_DayCare/scripts.pory"
	.string "Will you take back the other one,\n"
# 552 "data/maps/Route34_DayCare/scripts.pory"
	.string "too?$"
# 553 "data/maps/Route34_DayCare/scripts.pory"

# 554 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_ComeAgain:
# 555 "data/maps/Route34_DayCare/scripts.pory"
	.string "Fine.\n"
# 556 "data/maps/Route34_DayCare/scripts.pory"
	.string "Come again.$"
# 557 "data/maps/Route34_DayCare/scripts.pory"

# 558 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_GoodToSeeYou:
# 559 "data/maps/Route34_DayCare/scripts.pory"
	.string "Ah, it's you! Good to see you.\n"
# 560 "data/maps/Route34_DayCare/scripts.pory"
	.string "Your Pokémon can only be doing good!$"
# 561 "data/maps/Route34_DayCare/scripts.pory"

# 562 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_YourMonHasGrownXLevels:
# 563 "data/maps/Route34_DayCare/scripts.pory"
	.string "By level, your {STR_VAR_1} has\n"
# 564 "data/maps/Route34_DayCare/scripts.pory"
	.string "grown by {STR_VAR_2}.$"
# 565 "data/maps/Route34_DayCare/scripts.pory"

# 566 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_YourTeamIsFull:
# 567 "data/maps/Route34_DayCare/scripts.pory"
	.string "Your Pokémon team is full.\n"
# 568 "data/maps/Route34_DayCare/scripts.pory"
	.string "Make room, then come see me.$"
# 569 "data/maps/Route34_DayCare/scripts.pory"

# 570 "data/maps/Route34_DayCare/scripts.pory"
@ Unused
# 571 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_TakeBackWhichMon:
# 572 "data/maps/Route34_DayCare/scripts.pory"
	.string "Which Pokémon will you take back?$"
# 573 "data/maps/Route34_DayCare/scripts.pory"

# 574 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_ItWillCostX:
# 575 "data/maps/Route34_DayCare/scripts.pory"
	.string "If you want your {STR_VAR_1} back,\n"
# 576 "data/maps/Route34_DayCare/scripts.pory"
	.string "it will cost ¥{STR_VAR_2}.$"
# 577 "data/maps/Route34_DayCare/scripts.pory"

# 578 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_HeresYourMon:
# 579 "data/maps/Route34_DayCare/scripts.pory"
	.string "Perfect!\n"
# 580 "data/maps/Route34_DayCare/scripts.pory"
	.string "Here's your Pokémon.$"
# 581 "data/maps/Route34_DayCare/scripts.pory"

# 582 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_TookBackMon:
# 583 "data/maps/Route34_DayCare/scripts.pory"
	.string "{PLAYER} took back {STR_VAR_1} from\n"
# 584 "data/maps/Route34_DayCare/scripts.pory"
	.string "the Day-Care Lady.$"
# 585 "data/maps/Route34_DayCare/scripts.pory"

# 586 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_YouHaveJustOneMon:
# 587 "data/maps/Route34_DayCare/scripts.pory"
	.string "Oh? But you have just one\n"
# 588 "data/maps/Route34_DayCare/scripts.pory"
	.string "Pokémon.\p"
# 589 "data/maps/Route34_DayCare/scripts.pory"
	.string "Come back another time.$"
# 590 "data/maps/Route34_DayCare/scripts.pory"

# 591 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_TakeYourMonBack:
# 592 "data/maps/Route34_DayCare/scripts.pory"
	.string "Will you take your Pokémon back?$"
# 593 "data/maps/Route34_DayCare/scripts.pory"

# 594 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_WhatWillYouBattleWith:
# 595 "data/maps/Route34_DayCare/scripts.pory"
	.string "If you leave me that Pokémon,\n"
# 596 "data/maps/Route34_DayCare/scripts.pory"
	.string "what will you battle with?\p"
# 597 "data/maps/Route34_DayCare/scripts.pory"
	.string "Come back another time.$"
# 598 "data/maps/Route34_DayCare/scripts.pory"

# 599 "data/maps/Route34_DayCare/scripts.pory"
Route34_DayCare_Text_YoullBeLeftWithJustOne:
# 600 "data/maps/Route34_DayCare/scripts.pory"
	.string "Huh?\n"
# 601 "data/maps/Route34_DayCare/scripts.pory"
	.string "Now, now.\p"
# 602 "data/maps/Route34_DayCare/scripts.pory"
	.string "If you leave that Pokémon with\n"
# 603 "data/maps/Route34_DayCare/scripts.pory"
	.string "me, you'll be left with just one.\p"
# 604 "data/maps/Route34_DayCare/scripts.pory"
	.string "You will be better off if you catch\n"
# 605 "data/maps/Route34_DayCare/scripts.pory"
	.string "some more, I dare say.$"

daycareDestinyKnotGift::
# 609 "data/maps/Route34_DayCare/scripts.pory"
	lock
# 610 "data/maps/Route34_DayCare/scripts.pory"
	faceplayer
# 611 "data/maps/Route34_DayCare/scripts.pory"
	goto_if_set FLAG_DESTINYKNOT_GIFT, daycareDestinyKnotGift_2
# 617 "data/maps/Route34_DayCare/scripts.pory"
	msgbox daycareDestinyKnotGift_Text_1
# 623 "data/maps/Route34_DayCare/scripts.pory"
	giveitem ITEM_DESTINY_KNOT
# 624 "data/maps/Route34_DayCare/scripts.pory"
	setflag FLAG_DESTINYKNOT_GIFT
# 625 "data/maps/Route34_DayCare/scripts.pory"
	msgbox daycareDestinyKnotGift_Text_0
# 627 "data/maps/Route34_DayCare/scripts.pory"
	waitmessage
# 628 "data/maps/Route34_DayCare/scripts.pory"
	release
	end

daycareDestinyKnotGift_2:
# 612 "data/maps/Route34_DayCare/scripts.pory"
	msgbox daycareDestinyKnotGift_Text_0
# 614 "data/maps/Route34_DayCare/scripts.pory"
	release
	end


daycareDestinyKnotGift_Text_0:
# 612 "data/maps/Route34_DayCare/scripts.pory"
	.string "Destiny Knot will let Pokémon inherit\n"
	.string "5 Innate values from their parents.$"

daycareDestinyKnotGift_Text_1:
# 617 "data/maps/Route34_DayCare/scripts.pory"
	.string "Hey! Have you tried putting your\n"
	.string "Pokémon into daycare yet? Sometimes\l"
	.string "the daycare couple might find an egg.\p"
	.string "If you plan to hoard a lot of eggs,\n"
	.string "you might find this useful.$"
