RailwayCave_Registeel_Room_MapScripts::
	.byte 0


RegisteelChamber_Registeel::
# 4 "data/maps/RailwayCave_Registeel_Room/scripts.pory"
	lock
# 5 "data/maps/RailwayCave_Registeel_Room/scripts.pory"
	faceplayer
# 6 "data/maps/RailwayCave_Registeel_Room/scripts.pory"
	legendaryencounter SPECIES_REGISTEEL, 50, 1, FLAG_HIDE_REGISTEEL
# 7 "data/maps/RailwayCave_Registeel_Room/scripts.pory"
	release
	end

